### ISSUE TITLE
[Bug]: Twitter Old Icon

### ISSUE THREAD

**Issue by harshbhar0629** [Bitbox-Connect/Bitbox#107]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Website using old icon of twitter it's not using updated icon of twitter.

### Expected behavior

I want to replace the old twitter icon to new twitter icon.

### Add screenshots (if applicable)

![twitterIcon](https://github.com/user-attachments/assets/4a4c2c13-e10b-48cd-a162-95b8110f1854)

### Confirmation

- [X] I have read the Bitbox Contributing Guidelines
- [X] I am a GSSOC-EXT contributor
- [X] I am a HACKTOBERFEST contributor
- [X] I have starred the Bitbox repository

**Comment by Anuj3553** [comment]
Hyy @harshbhar0629, I'm assigning this issue to you.
