### ISSUE TITLE
[Bug]: Default Profile image

### ISSUE THREAD

**Issue by harshbhar0629** [Bitbox-Connect/Bitbox#108]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When user creates an account then website show profile image and that image is not a logged in user.

### Expected behavior

I want to replace that image to the custom image which is generate by api by using their name of alphabets.
EX: Harsh Bhardwaj then image will show to me HB.
EX: Bitbox Connect then image will show to me BC.

### Add screenshots (if applicable)

![profileImage](https://github.com/user-attachments/assets/99a848df-2a6e-4f29-800d-734121224d9a)

### Confirmation

- [X] I have read the Bitbox Contributing Guidelines
- [X] I am a GSSOC-EXT contributor
- [X] I am a HACKTOBERFEST contributor
- [X] I have starred the Bitbox repository

**Comment by Anuj3553** [comment]
Hyy @harshbhar0629, I'm assigning this issue to you.
