### ISSUE TITLE
[Feature Request]: Addition of .env_sample file in server

### ISSUE THREAD

**Issue by vivekrawat21** [Bitbox-Connect/Bitbox#113]
### Is there an existing feature request for this?

- [X] I have searched the existing feature requests

### Describe the feature you would like to request

Currently, contributors do not have a reference for required environment variables, which can lead to setup confusion or misconfigurations. I want to add a .env_sample file in server 

### What problem does this feature solve?

To streamline the development process, we should add an env_sample file that outlines the necessary environment variables without sensitive data. Create an env_sample file in the root of the project server folder.
Include placeholders for all required environment variables.
Add documentation in the file explaining what each variable does and any necessary values or formats.
Ensure sensitive data is not included—use placeholders (e.g., YOUR_API_KEY_HERE).
Update the README.md with a section on how to use the env_sample file.

Additional context
Benefits:
Improves onboarding for new contributors.
Prevents setup issues related to missing or incorrect environment variables.

### Confirmation

- [X] I have read the Bitbox Contributing Guidelines
- [X] I am a GSSOC-EXT contributor
- [X] I am a HACKTOBERFEST contributor
- [X] I have starred the Bitbox repository
- [X] I would like to help implement this feature

**Comment by Anuj3553** [comment]
Hyy @vivekrawat21, I'm assigning this issue to you.
