### ISSUE TITLE
[Feature Request]: Addition of Progress Bar | That Represent Content/Page Depth

### ISSUE THREAD

**Issue by Shariq2003** [Bitbox-Connect/Bitbox#114]
### Is there an existing feature request for this?

- [X] I have searched the existing feature requests

### Describe the feature you would like to request

I want to add a progress bar at the top of the website just like in GSSOC Website

![image](https://github.com/user-attachments/assets/45e2e3bf-3bb0-44d8-8b0d-2de61fa9f469)

Look at the top

### What problem does this feature solve?

.

### Confirmation

- [X] I have read the Bitbox Contributing Guidelines
- [X] I am a GSSOC-EXT contributor
- [X] I am a HACKTOBERFEST contributor
- [X] I have starred the Bitbox repository
- [X] I would like to help implement this feature

**Comment by Anuj3553** [comment]
Hyy @Shariq2003, I'm assigning this issue to you.

**Comment by Shariq2003** [comment]
> Hyy @Shariq2003, I'm assigning this issue to you.

Thanks sir

**Comment by Shariq2003** [comment]
Please review my PR and merge
