### ISSUE TITLE
Inconsistent Design and Usability Issues in Login and Signup UI

### ISSUE THREAD

**Issue by SRV30** [Bitbox-Connect/Bitbox#124]
### Is there an existing feature request for this?

- [X] I have searched the existing feature requests

### Describe the feature you would like to request

I will adjust the colors to perfectly match the theme, whether it's light or dark.

### What problem does this feature solve?

Login Page in light mode - 
![image](https://github.com/user-attachments/assets/639d32a4-9e9c-4090-9d37-8c3471aae1f1)

Login Page in dark mode - 
![image](https://github.com/user-attachments/assets/b593674a-c8ee-4c5f-8a42-d17fd839991d)

same as for signup
![image](https://github.com/user-attachments/assets/51d08b35-169f-4e89-a05b-3e8938a3b7a7)

![Uploading image.png…]()

### Confirmation

- [X] I have read the Bitbox Contributing Guidelines
- [X] I am a GSSOC-EXT contributor
- [X] I am a HACKTOBERFEST contributor
- [X] I have starred the Bitbox repository
- [X] I would like to help implement this feature

**Comment by SRV30** [comment]
Also adding features of an "eye" icon (👁️) for showing and hiding button on both the pages

**Comment by SRV30** [comment]
please assign this to me

**Comment by Anuj3553** [comment]
Hyy @SRV30, I'm assigning this issue to you.

**Comment by Anuj3553** [comment]
Can you give star to this repo?

**Comment by SRV30** [comment]
thank u for assigning me and also given u star
