### ISSUE TITLE
[Bug]: Responsiveness problem

### ISSUE THREAD

**Issue by krishpathak** [Bitbox-Connect/Bitbox#130]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

in mobile view some portion gets hidden under the navbar i will fix it
![image](https://github.com/user-attachments/assets/6d619481-1f88-4b85-a8f4-1d1a3eba98d3)

### Expected behavior

fixed 
![image](https://github.com/user-attachments/assets/5a016c9d-276e-41f4-8280-c83830817433)
@Anuj3553  kindly assign me task.

### Confirmation

- [X] I have read the Bitbox Contributing Guidelines
- [X] I am a GSSOC-EXT contributor
- [X] I am a HACKTOBERFEST contributor
- [X] I have starred the Bitbox repository

**Comment by Anuj3553** [comment]
Hyy @krishpathak , I'm assigning this issue to you.

**Comment by Anuj3553** [comment]
Can you give star to this repo?

**Comment by krishpathak** [comment]
Yeah i will star the repo

**Comment by krishpathak** [comment]
Can you please add level 2?
