### ISSUE TITLE
Fixes In BackToTop Button (Hard Scroll) | Dark/Light Mode Icon Enhancment | Card Hover Effect Addition | 

### ISSUE THREAD

**Issue by Shariq2003** [Bitbox-Connect/Bitbox#134]
I want to fix the following :-

1. Fixes In BackToTop Button (Hard Scroll), Scrolling is not smooth, just sets the Y value to 0 and get at the top.
2. Dark/Light Mode Icon Enhancement. Icons should be of bright colors.
3. Card hover effect missing in community section.

https://github.com/user-attachments/assets/24b73dca-3864-445d-a2d6-b670a0f7ea83

**Comment by AliAbushariaa** [comment]
Can I work on the second issue ?

**Comment by Shariq2003** [comment]
> Can I work on the second issue ?

No, I have to work on all.
You can also find other issues and create them.

**Comment by Anuj3553** [comment]
Hyy @Shariq2003, I'm assigning this issue to you. Can you give star to this repo?

**Comment by Anuj3553** [comment]
Can you use lenis for smooth scrolling? https://github.com/darkroomengineering/lenis

**Comment by Shariq2003** [comment]
> Can you use lenis for smooth scrolling? https://github.com/darkroomengineering/lenis

No sir, I am going add an function that changes the Y value in an manner depends on the current height of the page, and add an smoth transitions animation for this change making it smoth

**Comment by Shariq2003** [comment]
> Can you use lenis for smooth scrolling? https://github.com/darkroomengineering/lenis

But if you want me to use lenis then I can also use that

**Comment by Anuj3553** [comment]
> > Can you use lenis for smooth scrolling? https://github.com/darkroomengineering/lenis
> 
> But if you want me to use lenis then I can also use that

Thankyou @Shariq2003
