### ISSUE TITLE
[Feature Request]: Email Validation Addition | React Toast Alerts Addition in Contact Us Form.

### ISSUE THREAD

**Issue by Shariq2003** [Bitbox-Connect/Bitbox#135]
### Is there an existing feature request for this?

- [X] I have searched the existing feature requests

### Describe the feature you would like to request

1. Email Validation Addition in the contact us page.
2.  React Toast Alerts Addition.

### What problem does this feature solve?

https://github.com/user-attachments/assets/93ebfbbc-894c-4ca4-b2bc-59ac6a39ff62

### Confirmation

- [X] I have read the Bitbox Contributing Guidelines
- [X] I am a GSSOC-EXT contributor
- [X] I am a HACKTOBERFEST contributor
- [X] I have starred the Bitbox repository
- [X] I would like to help implement this feature

**Comment by Anuj3553** [comment]
Hyy @Shariq2003, I'm assigning this issue to you. Can you give star to this repo?

**Comment by Shariq2003** [comment]
> Hyy @Shariq2003, I'm assigning this issue to you. Can you give star to this repo?
Okay sir

**Comment by Shariq2003** [comment]
@Anuj3553 assign me on this

**Comment by Anuj3553** [comment]
> @Anuj3553 assign me on this

Done ✌️
