### ISSUE TITLE
Add a CONTRIBUTING.md File for Contribution Guidelines

### ISSUE THREAD

**Issue by Varsha567** [Bitbox-Connect/Bitbox#14]
To streamline the contribution process, I suggest adding a CONTRIBUTING.md file. This would provide clear guidelines for new contributors, including steps for setting up the project locally, coding standards, and how to raise issues or submit pull requests. This document can improve the onboarding process for open-source contributors, making it easier to contribute effectively.

Could you please assign this to me?

**Comment by Anuj3553** [comment]
Hey @Varsha567,

Thank you for the suggestion! We appreciate your initiative. We're assigning this issue to you—looking forward to seeing your contribution!

**Comment by Anuj3553** [comment]
Well done, @Varsha567 , on completing the issue! 🎉
Your efforts are truly valued, and the updates you implemented look excellent. Keep up the great work, and continue contributing your talents!

**Comment by Varsha567** [comment]
Hii @Anuj3553  I noticed that my contributions are not reflected on the leaderboard, and I would like to kindly request your assistance in rectifying this issue. It’s important for me to have my contributions acknowledged, and I believe they have met the required criteria.
Thank you for your attention to this matter. I appreciate your support, and I look forward to your response.

**Comment by Anuj3553** [comment]
Hyy @Varsha567, Can you do star mark this repo?

**Comment by Varsha567** [comment]
> Hyy @Varsha567, Can you do star mark this repo?

Already done!
