### ISSUE TITLE
Navbar Enhancement | UI is messing Up in Light Mode | Login/SignUp Button's Text Not Visibile | Unwanted Border of Navbar

### ISSUE THREAD

**Issue by Shariq2003** [Bitbox-Connect/Bitbox#140]
The Navbar contains the following issues, that i want to fix :-

1. UI is messing Up in Light Mode.
2. Login/SignUp Button's Text not visibile.
3. Unwanted Border of Navbar.

https://github.com/user-attachments/assets/3cf8b273-9b04-45fb-b501-15f08a24bdec

**Comment by Anuj3553** [comment]
Hyy @Shariq2003, I'm assigning this issue to you.
