### ISSUE TITLE
Website Scrollbar Customisation | Theme Matched Scrollbar Customisation

### ISSUE THREAD

**Issue by Shariq2003** [Bitbox-Connect/Bitbox#145]
![image](https://github.com/user-attachments/assets/ab1f558a-3ffb-403a-a76c-3502c2cb546a)

The current Scrollbar is not looking good and also not match with the theme of the website.

I want to customize this according to the website.

**Comment by Anuj3553** [comment]
Hyy @Shariq2003, I'm assigning this issue to you.
