### ISSUE TITLE
Add Hover function to the nav var.

### ISSUE THREAD

**Issue by harshbhardwaj000** [Bitbox-Connect/Bitbox#147]

**Comment by harshbhardwaj000** [comment]
![Screenshot 2024-10-17 212357](https://github.com/user-attachments/assets/87931f27-1fb6-40c3-b807-65de6ce1cce6)

**Comment by Anuj3553** [comment]
Hyy @harshbhardwaj000, I'm assigning this issue to you.

**Comment by Anuj3553** [comment]
Can you give star to this repo?

**Comment by harshbhardwaj000** [comment]
Yes i will😊

**Comment by harjasae2001** [comment]
Can u reassign this issue to me. I really want to contribute to this project

**Comment by Anuj3553** [comment]
> Can u reassign this issue to me. I really want to contribute to this project

Please show us the sample work that what do you want.

**Comment by harjasae2001** [comment]
https://codepen.io/harjasae2001/pen/MWNOZgR

https://codepen.io/harjasae2001/pen/poMdqzq

Here are some sample. You can let me know which one should I apply.

**Comment by Anuj3553** [comment]
![image](https://github.com/user-attachments/assets/0b5c0490-3db0-46bc-8932-7ca664face6a)

Third Number --> https://codepen.io/harjasae2001/pen/MWNOZgR

**Comment by harjasae2001** [comment]
Okay, Can u pls assign me this issue.

**Comment by Anuj3553** [comment]
> Okay, Can u pls assign me this issue.

Done ;)
