### ISSUE TITLE
[Feature Request]: Add Multi-Language Support for Global Accessibility

### ISSUE THREAD

**Issue by sezallagwal** [Bitbox-Connect/Bitbox#151]
### Is there an existing feature request for this?

- [X] I have searched the existing feature requests

### Describe the feature you would like to request

Implement multi-language support , allowing users from different regions to interact with the website in their preferred language. This feature will enhance accessibility and usability, making it easier for non-English-speaking users to browse the site.

### What problem does this feature solve?

Set up a language selection dropdown or toggle in the header/footer for easy switching.
Store language preferences using cookies or local storage.
Ensure that the translated content adapts dynamically based on the selected language.

### Alternative solutions

please assign this to me under gssoc-ext and hacktoberfest

### Confirmation

- [X] I have read the Bitbox Contributing Guidelines
- [X] I am a GSSOC-EXT contributor
- [X] I am a HACKTOBERFEST contributor
- [X] I have starred the Bitbox repository
- [X] I would like to help implement this feature

**Comment by Harshit7492** [comment]
Hello @sezallagwal please add some screenshots for this issue

**Comment by sezallagwal** [comment]
![image](https://github.com/user-attachments/assets/004b9771-740d-4afb-a43f-6df1777d692a)
@Harshit7492

**Comment by Harshit7492** [comment]
@sezallagwal: When changing the country name, please ensure that the language setting is also updated accordingly. Thank you!

**Comment by Anuj3553** [comment]
Hyy @sezallagwal, I'm assigning this issue to you. Can you give star to this repo?

**Comment by sezallagwal** [comment]
okay will do it but I have my exams going on till 24 so I might be a bit slow. Is that okay with you @Anuj3553 @Harshit7492

**Comment by Anuj3553** [comment]
> okay will do it but I have my exams going on till 24 so I might be a bit slow. Is that okay with you @Anuj3553 @Harshit7492

Yes, you can take your time but careful about the date because gssoc is ended by this month end. All the best for your exams ✌️.
