### ISSUE TITLE
[Feature Request]:  Enhanced Collaboration Features

### ISSUE THREAD

**Issue by sezallagwal** [Bitbox-Connect/Bitbox#152]
### Is there an existing feature request for this?

- [X] I have searched the existing feature requests

### Describe the feature you would like to request

To improve collaboration and project management on the Bitbox platform, we propose adding the following features:

Live Code Collaboration
Integrate a live code editor to facilitate real-time coding and problem-solving sessions. This will enable users to work together simultaneously on the same codebase, enhancing productivity and learning.

Team Workspaces
Create private workspaces for teams where members can collaborate on projects without external distractions. The workspace should include discussion boards, task management tools, and file sharing to streamline project workflows.

Project Showcase
Introduce a Project Showcase section where users can display completed projects or ongoing work. The showcase should support detailed project descriptions, media uploads (e.g., images, videos), and project links, allowing users to highlight their accomplishments and attract potential collaborators.

### What problem does this feature solve?

Phase 1: Research and choose a real-time code editor solution (e.g., Monaco, CodeMirror).
Phase 2: Develop the private team workspace feature, including discussion boards and file sharing.
Phase 3: Design and implement the Project Showcase with media support.

### Alternative solutions

lables: 
hacktoberfest
gssoc-ext

### Confirmation

- [X] I have read the Bitbox Contributing Guidelines
- [X] I am a GSSOC-EXT contributor
- [X] I am a HACKTOBERFEST contributor
- [X] I have starred the Bitbox repository
- [X] I would like to help implement this feature

**Comment by Harshit7492** [comment]
please add some screenshots for solving this issue @sezallagwal
