### ISSUE TITLE
[Feature Request]: Improve the Footer Design on the Main Page

### ISSUE THREAD

**Issue by anothercoder-nik** [Bitbox-Connect/Bitbox#157]
### Is there an existing feature request for this?

- [X] I have searched the existing feature requests

### Describe the feature you would like to request

The current footer on the main page lacks clarity and responsiveness. It could be enhanced to improve usability and aesthetics, especially on smaller screens.

### What problem does this feature solve?

**Problem This Feature Solves:**
The current footer design presents several issues that impact usability and accessibility:

1. *Poor User Experience on Mobile Devices*: The footer is not fully responsive, leading to misalignment or cluttered content on smaller screens, making it hard for users to interact with important elements.
2. *Lack of Structure*: The footer lacks clear organization, causing users to struggle when finding essential information like contact details, useful links, or social media pages.
3. *Readability and Accessibility Concerns*: Insufficient spacing, small font sizes, and low contrast may cause readability issues, particularly for users with visual impairments or on mobile devices.
4. *Inconsistent Footer Visibility*: On longer pages, users must scroll to the bottom to access the footer. A sticky footer would provide a better experience by keeping key links always accessible.

By implementing this feature, the footer will be more user-friendly, accessible, and organized across all devices and screen sizes, improving the overall user experience.

**Suggested Improvements:**

- *Enhanced Responsiveness*: Ensure the footer adapts well to different screen sizes, especially on mobile devices. Elements should remain properly aligned and spaced.
-*Improved Layout*: Organize the footer content into distinct sections, such as:
"About Us"
"Contact Information"
"Useful Links"
"Social Media Links"
- *Sticky Footer*: Implement an option to make the footer sticky so that it remains visible at the bottom of the page as the user scrolls.
- *Increased Readability*: Improve padding, margin, and font sizes for better readability and accessibility, ensuring sufficient contrast between text and background.
- *Add Social Media Icons/Links*: Incorporate social media icons with quick links to platforms, as well as important links like "Terms of Service" and "Privacy Policy."

Examples of some reponsive footers - 
![mobile](https://github.com/user-attachments/assets/aec16fab-3750-472e-8b28-55d4fe74b237)
![des](https://github.com/user-attachments/assets/39cb2e4f-23c3-4c07-92d4-441dfac970cd)

### Confirmation

- [X] I have read the Bitbox Contributing Guidelines
- [X] I am a GSSOC-EXT contributor
- [X] I am a HACKTOBERFEST contributor
- [X] I have starred the Bitbox repository
- [X] I would like to help implement this feature

**Comment by Harshit7492** [comment]
can you add screenshots of footer to @Harshit7492 ,
 so that it is easy to understand where it is lacking @anothercoder-nik

**Comment by anothercoder-nik** [comment]
Look according to my experience in project building for a first time user , this footer might not that engaging as sometimes user tend to find crucial things on footer.

Second look on this when i am on mobile , footer got messed up-

![mobile](https://github.com/user-attachments/assets/0322052c-9b35-4f1c-b68e-58dded09ef34)

**Comment by Harshit7492** [comment]
we add all the lables which are required please complete it first

**Comment by anothercoder-nik** [comment]
ok sure no issue

**Comment by anothercoder-nik** [comment]
Hii @Anuj3553 , I just opened a Pull Request with your correct format of PR description but idk why your pr checker and 
netlify bot failing my PR, Can you help please!

**Comment by Anuj3553** [comment]
> Hii @Anuj3553 , I just opened a Pull Request with your correct format of PR description but idk why your pr checker and netlify bot failing my PR, Can you help please!

I think your query is solved? If not then tell us our problem.

**Comment by anothercoder-nik** [comment]
hey @Anuj3553  my pr is merged now by @Harshit7492 , thanks to you guys , my only issue is ,  plz attach gssoc and hacktoberfest labels in my PR that is merged, because on leaderboard it is not counted yet . Please

**Comment by Anuj3553** [comment]
> hey @Anuj3553 my pr is merged now by @Harshit7492 , thanks to you guys , my only issue is , plz attach gssoc and hacktoberfest labels in my PR that is merged, because on leaderboard it is not counted yet . Please

I have already attached the necessary labels.

**Comment by Anuj3553** [comment]
> hey @Anuj3553 my pr is merged now by @Harshit7492 , thanks to you guys , my only issue is , plz attach gssoc and hacktoberfest labels in my PR that is merged, because on leaderboard it is not counted yet . Please

Please wait for some time for updating the leaderboard. If you faced any difficulty further then feel free to reach me from my any social account.
