### ISSUE TITLE
[Bug] text overlapping outside the div

### ISSUE THREAD

**Issue by Vinayyy19** [Bitbox-Connect/Bitbox#166]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

text overlapping outside the div

### Expected behavior

text should fix under div

### Add screenshots (if applicable)

![image](https://github.com/user-attachments/assets/98f8c51b-4942-4984-ac5e-671875954240)

### Confirmation

- [X] I have read the Bitbox Contributing Guidelines
- [X] I am a GSSOC-EXT contributor
- [X] I am a HACKTOBERFEST contributor
- [X] I have starred the Bitbox repository

**Comment by Vinayyy19** [comment]
i would like to work on this issue can you assign me with gssoc and hacktoberfest label

**Comment by Anuj3553** [comment]
Hyy @Vinayyy19, I'm assigning this issue to you.

**Comment by Anuj3553** [comment]
Can you give star to this repo?

**Comment by SnehaPatil47** [comment]
can you assign me this

**Comment by Anuj3553** [comment]
> can you assign me this

Sorry @SnehaPatil47, Already assigned to @Vinayyy19 this issue.

**Comment by SnehaPatil47** [comment]
It's okay
