### ISSUE TITLE
I want to add scroll animation effects for hero and bitbox community section.

### ISSUE THREAD

**Issue by varma-101** [Bitbox-Connect/Bitbox#167]

**Comment by Anuj3553** [comment]
Hyy @varma-101, I'm assigning this issue to you.

**Comment by varma-101** [comment]
@Anuj3553  bro navbar is clumsy when i cloned this repo.

**Comment by varma-101** [comment]
I've completed the work i am making a detailed pr please review it.

**Comment by varma-101** [comment]
Now start issue no #168

**Comment by Anuj3553** [comment]
> Now start issue no #168

What do  you mean @varma-101

**Comment by varma-101** [comment]
I have completed my work brother. the person in the issue no raised a similar after my issue maybe they will do for remaining cards. i've already completed and gave you a pr . please verify it i've attached a video description for your better understanding.

**Comment by Anuj3553** [comment]
> I have completed my work brother. the person in the issue no raised a similar after my issue maybe they will do for remaining cards. i've already completed and gave you a pr . please verify it i've attached a video description for your better understanding.

Done ✌️
