### ISSUE TITLE
[Bug]: Bad alignment in discussion page

### ISSUE THREAD

**Issue by harshbhar0629** [Bitbox-Connect/Bitbox#169]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

There is bad alignment of discussion page send btn lie in footer.

### Expected behavior

When we render discussion page then it will have some padding from bottom

### Add screenshots (if applicable)

![badAlignment](https://github.com/user-attachments/assets/94f456de-f81d-4938-b6bf-a2e707c470ec)

### Confirmation

- [X] I have read the Bitbox Contributing Guidelines
- [X] I am a GSSOC-EXT contributor
- [X] I am a HACKTOBERFEST contributor
- [X] I have starred the Bitbox repository

**Comment by harshbhar0629** [comment]
@Anuj3553 Please assign the label:)

**Comment by Anuj3553** [comment]
Hyy @harshbhar0629, I'm assigning this issue to you.

**Comment by Anuj3553** [comment]
Can you give the star to the repo?

**Comment by harshbhar0629** [comment]
Already done:)

**Comment by Anuj3553** [comment]
> Already done:)

Thankyou bro
