### ISSUE TITLE
Null User Error on the discussion page and adding a modal to the page

### ISSUE THREAD

**Issue by SurajSakhare100** [Bitbox-Connect/Bitbox#17]
![bitbox](https://github.com/user-attachments/assets/7036baa5-2b5a-479e-b640-b3252bac3e84)

@Anuj3553 
When navigating to the **discussion** page, if a user doesn't enter a name, it results in a **null user bug**. I'd like to resolve this bug by adding **more validation** to prevent it. Additionally, I can **implement a modal** for this issue since **using an alert is not the best option.** You can assign this to me under **GSSoC and Hacktoberfest**

**Comment by Anuj3553** [comment]
Thank you for pointing this out, @SurajSakhare100! I agree that additional validation and implementing a modal would be a great solution. I have assigned this issue to you under GSSoC and Hacktoberfest. Looking forward to seeing the fix!

**Comment by SurajSakhare100** [comment]
https://github.com/user-attachments/assets/66295bc0-850c-4ed4-91f3-2071edf6dd17

**Solve null user issue with Modal..**

@Anuj3553  please add hactoberfest label to it..

can i make PR

**Comment by Anuj3553** [comment]
Hyy @SurajSakhare100, 
Can you make a minor change make the button and input border blue as our website color template.

**Comment by SurajSakhare100** [comment]
@Anuj3553 ya sure

**Comment by Anuj3553** [comment]
Well done, @SurajSakhare100, on completing the issue! 🎉
Your efforts are truly valued. Keep up the great work, and continue contributing your talents!
