### ISSUE TITLE
[Feature Request]: Authentication with Google and Other Providers (OAuth Integration)

### ISSUE THREAD

**Issue by amitb0ra** [Bitbox-Connect/Bitbox#173]
### Is there an existing feature request for this?

- [X] I have searched the existing feature requests

### Describe the feature you would like to request

As mentioned in **#35**, @Grandhi-Harshitha encountered difficulties implementing this feature, so I am raising this issue to address it.

I would like to request the addition of third-party authentication support, specifically through OAuth-based providers such as Google, Facebook, GitHub, and others. This feature would allow users to register or log in using their existing accounts with these providers, eliminating the need to create a new password and profile. The integration will streamline the onboarding process, enhance account security, and provide a smoother, more efficient login experience.

### What problem does this feature solve?

Currently, users are required to create an entirely new account with a unique password to sign up or log in. This can be a point of friction for new users who might prefer to avoid the hassle of creating yet another account. Additionally, managing passwords can be a security concern for users who might reuse weak passwords. 

By allowing users to sign up or log in using trusted third-party accounts (e.g., Google), the platform can:
- Reduce the likelihood of account abandonment during registration.
- Improve security, as users will rely on the strong authentication protocols of major providers.
- Enhance the user experience by offering faster, password-free access.

### Alternative solutions

**Manual Account Creation**  
The current solution is to have users manually create accounts by entering an email address and password. While this method works, it places the burden of creating and managing passwords on the users. It also doesn’t address the convenience or speed that OAuth can offer.

### Confirmation

- [X] I have read the Bitbox Contributing Guidelines
- [X] I am a GSSOC-EXT contributor
- [X] I am a HACKTOBERFEST contributor
- [X] I have starred the Bitbox repository
- [X] I would like to help implement this feature

**Please assign this issue to me for Hacktoberfest and GSoC-ext.**

**Comment by Anuj3553** [comment]
Hyy @amitb0ra, I'm assigning this issue to you. Please provide the video of working auth when your are doing PR. All the best @amitb0ra :)

**Comment by Anuj3553** [comment]
Can you give star to this repo?

**Comment by amitb0ra** [comment]
> Can you give star to this repo?

already i have starred this repo.
