### ISSUE TITLE
[Bug]: Persistent Dark Mode Across Page Refreshes

### ISSUE THREAD

**Issue by amitb0ra** [Bitbox-Connect/Bitbox#174]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When using Bitbox, the dark mode setting resets to the light theme every time the page is refreshed. This results in a loss of user preference, requiring users to manually re-enable dark mode after each refresh or navigation.

### Expected behavior

I expected that once I enabled dark mode in Bitbox, the application would retain this setting even after refreshing the page or navigating to different sections. The theme should remain consistent, allowing for a seamless user experience without needing to toggle the setting repeatedly.

### Add screenshots (if applicable)

https://github.com/user-attachments/assets/8cbe95c4-8ea0-4072-bb55-602118423ba6

### On which device or platform are you experiencing this bug?

Android, iPhone, Linux, Chrome, Windows

### Confirmation

- [X] I have read the Bitbox Contributing Guidelines
- [X] I am a GSSOC-EXT contributor
- [X] I am a HACKTOBERFEST contributor
- [X] I have starred the Bitbox repository

**Please assign this issue to me for Hacktoberfest and GSoC-ext.**

**Comment by Anuj3553** [comment]
Hyy @amitb0ra, I'm assigning this issue to you.
