### ISSUE TITLE
[Bug]: Responsiveness Issue on Different Screen Sizes

### ISSUE THREAD

**Issue by amitb0ra** [Bitbox-Connect/Bitbox#175]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Bitbox is experiencing responsiveness issues when viewed on different screen sizes (e.g., mobile devices, tablets, or smaller window resolutions). Certain elements like buttons, text, and images either overlap, break layout, or do not scale properly, leading to a poor user experience on smaller screens.

### Expected behavior

I expected the Bitbox interface to adapt seamlessly to different screen sizes, maintaining proper alignment, visibility, and functionality of all UI elements. The application should adjust layout elements responsively, ensuring that the user interface is fully functional and visually consistent across devices, including mobile, tablet, and desktop.

### Add screenshots (if applicable)

![image](https://github.com/user-attachments/assets/07e65348-a89d-4b83-825d-31d4738eecbe)
![image](https://github.com/user-attachments/assets/fa0119d1-2fe1-4372-82d3-43226d38a10d)
![image](https://github.com/user-attachments/assets/4a26f670-2a8f-40c9-9213-a2363c5b6085)

### On which device or platform are you experiencing this bug?

Android, iPhone, Linux, Chrome, Windows

### Confirmation

- [X] I have read the Bitbox Contributing Guidelines
- [X] I am a GSSOC-EXT contributor
- [X] I am a HACKTOBERFEST contributor
- [X] I have starred the Bitbox repository

**Comment by Anuj3553** [comment]
Hyy @amitb0ra, I'm assigning this issue to you.
