### ISSUE TITLE
Add table of contents to the readme file

### ISSUE THREAD

**Issue by T-Fathima** [Bitbox-Connect/Bitbox#184]
### Is there an existing feature request for this?

- [X] I have searched the existing feature requests

### Describe the feature you would like to request

I would like to add table of contents sections to readme file for better readability and user experience.

I would like to work on it.
Please assign this issue to me under gssoc-ext and hacktoberfest.

### Confirmation

- [X] I have read the Bitbox Contributing Guidelines
- [X] I am a GSSOC-EXT contributor
- [X] I am a HACKTOBERFEST contributor
- [X] I have starred the Bitbox repository
- [X] I would like to help implement this feature

**Comment by Anuj3553** [comment]
Hyy @T-Fathima, I'm assigning this issue to you.
