### ISSUE TITLE
[Bug]: Improve Dark Mode Styling and Hover Effect for "Read More" Buttons on Home Page

### ISSUE THREAD

**Issue by kavya410004** [Bitbox-Connect/Bitbox#187]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

There are inconsistencies in the design of the "Read More" buttons on the home page when viewed in dark mode:

**1. Visibility Issue:** In dark mode, the "Read More" buttons are difficult to see, as their design merges with the background, making them less distinguishable and reducing the overall user experience.

**2. Lack of Hover Effect:** Currently, the "Read More" buttons do not have a hover effect, making them feel less interactive and not providing the feedback users expect when interacting with clickable elements.

### Expected behavior

- **Improved Button Visibility:** The "Read More" buttons should have a consistent design in dark mode, making them easily visible and ensuring they do not blend into the background.
- **Interactive Hover Effect:** Adding a hover effect to the buttons would enhance their interactivity. The hover effect should include a background color fill, making the button stand out when a user hovers over it, while maintaining a user-friendly appearance.

### Proposed Solution

I will resolve these issues by:

- Updating the button styles to ensure proper contrast and visibility in dark mode.
- Adding a hover effect that fills the background with a suitable color, improving user feedback when interacting with the buttons.

### Add screenshots (if applicable)

In light mode:
![image](https://github.com/user-attachments/assets/025557a1-1974-4dd3-8d81-e548d2341430)

In dark mode:
![image](https://github.com/user-attachments/assets/f1692fee-e52e-4081-918b-3aee089fedb2)

### On which device or platform are you experiencing this bug?

Windows

### Confirmation

- [X] I have read the Bitbox Contributing Guidelines
- [X] I am a GSSOC-EXT contributor
- [X] I am a HACKTOBERFEST contributor
- [X] I have starred the Bitbox repository

**Comment by kavya410004** [comment]
@Anuj3553 Could you please check this issue? I will work on it.

**Comment by Anuj3553** [comment]
Sorry @kavya410004, I changed already. I removed the read more button because it makes no sense here. If you wanna do another work let me know. But first you have to pull the code for keep updating.

**Comment by kavya410004** [comment]
> Sorry @kavya410004, I changed already. I removed the read more button because it makes no sense here. If you wanna do another work let me know. But first you have to pull the code for keep updating.

Okay. I was wondering if there is a discord group for this repo. If there is one, how can I join?

**Comment by kavya410004** [comment]
> Can you give star to the repo?

Sure

**Comment by kavya410004** [comment]
> Can you give star to the repo?

I have already starred it.
