### ISSUE TITLE
[Feature Request]:  Integrate Password Recovery Feature

### ISSUE THREAD

**Issue by saras-69** [Bitbox-Connect/Bitbox#189]
### Is there an existing feature request for this?

- [X] I have searched the existing feature requests

### Describe the feature you would like to request

This feature involves implementing a Password Recovery System that allows users to reset their password using an OTP or recovery link sent via email. After verification, users can create a new password and regain access to their accounts.

### What problem does this feature solve?

It addresses the issue of account lockouts due to forgotten passwords, improving the user experience and ensuring users don’t abandon the platform due to access issues.

### Alternative solutions

As an alternative, users could contact customer support to manually reset their passwords, but this is time-consuming and not user-friendly.

### Confirmation

- [X] I have read the Bitbox Contributing Guidelines
- [X] I am a GSSOC-EXT contributor
- [X] I am a HACKTOBERFEST contributor
- [X] I have starred the Bitbox repository
- [X] I would like to help implement this feature

Screenshots:

![Screenshot 2024-10-20 025545](https://github.com/user-attachments/assets/1a4f1f67-5737-4c3e-a180-73b9c42f82b9)
![Screenshot 2024-10-15 192639](https://github.com/user-attachments/assets/2ef4d190-bd11-4332-ae46-f298feebcc69)
![Screenshot 2024-10-15 022439](https://github.com/user-attachments/assets/c562d5f2-30fa-4277-81fd-1cf56b99e85f)
![Screenshot 2024-10-15 024732](https://github.com/user-attachments/assets/a587fe27-daa7-41d8-88be-8028f04022c0)

**Comment by Anuj3553** [comment]
Can you give star to this repo?

**Comment by saras-69** [comment]
> Can you give star to this repo?

sure
