### ISSUE TITLE
Improve Ui of Login And Sign up Form

### ISSUE THREAD

**Issue by iamsohelx** [Bitbox-Connect/Bitbox#19]
Hii @Anuj3553 in your website we can improve the ui of from making the user experience even better and adding smooth animation and transition on buttons.

## Screenshot
![newTask](https://github.com/user-attachments/assets/b2db3be9-1658-4f43-bcde-08929ea4d764)

**Comment by iamsohelx** [comment]
Hii @Anuj3553 Could you please assign this task to me. i wanted to work on this issue. : )

**Comment by Anuj3553** [comment]
Thank you for your suggestion, @iamsohelx! Improving the UI and adding smooth animations and transitions sounds like a great idea to enhance the user experience. I have assigned this task to you. Looking forward to your updates!

**Comment by iamsohelx** [comment]
@Anuj3553 Thank you brother.

it it good or should i change something?
![loginui](https://github.com/user-attachments/assets/06046260-7498-4684-ac64-54d089e6b218)

**Comment by Anuj3553** [comment]
![Singup Page](https://github.com/user-attachments/assets/b853e051-fd11-4a6c-82dc-4d8601f627f4)
![Login Page](https://github.com/user-attachments/assets/548467f1-6ce9-46e2-931e-2bc63ecda983)

Can you design like this @iamsohelx ?

**Comment by iamsohelx** [comment]
@Anuj3553 yeah sure

**Comment by Anuj3553** [comment]
I will provide code of designs if you needed ensure that login and signup is working.

**Comment by iamsohelx** [comment]
Ohh sure brother please give me code @Anuj3553

**Comment by Anuj3553** [comment]
Login Page -> 
import React from 'react';

const Login = () => {
    return (
        <div className="flex justify-center items-center h-screen bg-gray-100 relative overflow-hidden">
            <div className="relative z-10 h-[524px] w-[957px] border-primary border-2 flex bg-background shadow-lg rounded-2xl overflow-hidden max-w-4xl">
                <div className="absolute bg-primary z-0 clip-login-triangle w-full h-full"></div>
                {/* Left section (form) */}
                <div className="w-[60%] p-8 relative top-[10%] left-[5%]">
                    <div className="relative">
                        <h2 className="text-center text-[2.5rem] font-[800] text-primary mb-8">LOGIN</h2>
                        {/* Login heading underline */}
                        <div class="h-[0.4rem] w-[6rem] top-[3.5rem] rounded-[10px] left-[7rem] bg-primary absolute"></div>
                    </div>
                    <form>
                        {/* Username */}
                        <div class="space-y-3">
                            <div class="relative w-[20rem]">
                                <input type="email" class="peer py-3 pe-0 ps-8 block w-full bg-transparent border-t-transparent border-b-2 border-x-transparent border-b-gray-200 text-sm focus:border-t-transparent focus:border-x-transparent focus:border-b-blue-500 focus:ring-0 disabled:opacity-50 disabled:pointer-events-none dark:border-b-neutral-700 dark:text-neutral-400 dark:placeholder-neutral-500 dark:focus:ring-neutral-600 dark:focus:border-b-neutral-600" placeholder="USER NAME" />
                                <div class="absolute inset-y-0 start-0 flex items-center pointer-events-none ps-2 peer-disabled:opacity-50 peer-disabled:pointer-events-none">
                                    <svg class="shrink-0 size-4 text-gray-500 dark:text-neutral-500" xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
                                        <path d="M19 21v-2a4 4 0 0 0-4-4H9a4 4 0 0 0-4 4v2"></path>
                                        <circle cx="12" cy="7" r="4"></circle>
                                    </svg>
                                </div>
                            </div>

                            <div class="relative">
                                <input type="password" class="peer py-3 pe-0 ps-8 block w-full bg-transparent border-t-transparent border-b-2 border-x-transparent border-b-gray-200 text-sm focus:border-t-transparent focus:border-x-transparent focus:border-b-blue-500 focus:ring-0 disabled:opacity-50 disabled:pointer-events-none dark:border-b-neutral-700 dark:text-neutral-400 dark:placeholder-neutral-500 dark:focus:ring-neutral-600 dark:focus:border-b-neutral-600" placeholder="PASSWORD" />
                                <div class="absolute inset-y-0 start-0 flex items-center pointer-events-none ps-2 peer-disabled:opacity-50 peer-disabled:pointer-events-none">
                                    <svg class="shrink-0 size-4 text-gray-500 dark:text-neutral-500" xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
                                        <path d="M2 18v3c0 .6.4 1 1 1h4v-3h3v-3h2l1.4-1.4a6.5 6.5 0 1 0-4-4Z"></path>
                                        <circle cx="16.5" cy="7.5" r=".5"></circle>
                                    </svg>
                                </div>
                            </div>
                        </div>

                        {/* Links and buttons */}
                        <div className="flex justify-between text-sm mt-2 text-blue-500 uppercase">
                            <a href="#">Forgot Password</a>
                            <a href="/signup">Create Account</a>
                        </div>

                        {/* Login Button */}
                        <div className="mt-6">
                            <button className="w-full bg-primarybtn text-white py-2 px-4 rounded-full hover:bg-primary transition duration-300">
                                LOGIN
                            </button>
                        </div>

                        {/* Sign-up text */}
                        <div className="mt-6 text-center text-sm text-gray-600 uppercase">
                            Don&apos;t have an account?{' '}
                            <a href="/signup" className="text-primary font-bold">
                                Sign Up
                            </a>
                        </div>
                    </form>
                </div>

                {/* Right section (welcome text) */}
                <div className="text-black z-10 flex items-center justify-end p-8">
                    <div className="text-white flex flex-col items-end uppercase text-end">
                        <h2 className="text-6xl w-min ml-[-1.5rem] font-bold mb-2">WELCOME BACK !</h2>
                        <p className="text-sm w-[47%] text-end">
                            Lorem ipsum is simply dummy text of the printing and typesetting industry. Lorem ipsum has been the
                            industry&apos;s standard dummy.
                        </p>
                    </div>
                </div>
            </div>
        </div>
    );
};

export default Login;



Singup Page -> 

import React from "react";

const Signup = () => {
    return (
        <div className="flex justify-center items-center h-screen bg-gray-100">
            <div className="relative z-10 h-[524px] w-[957px] border-primary border-2 flex bg-background shadow-lg rounded-2xl overflow-hidden max-w-5xl">
                <div className="absolute bg-primary z-0 clip-signup-triangle w-full h-[524px]"></div>
                {/* Left Section */}
                <div className="w-1/2 p-[1rem] z-10 flex flex-col justify-center">
                    <h2 className="text-white text-6xl font-bold mb-6 w-min">WELCOME BACK !</h2>
                    <p className="w-[52.5%] text-white text-sm mb-10 uppercase">
                        Lorem ipsum is simply dummy text of the printing and typesetting
                        industry. Lorem ipsum has been the industry&apos;s standard dummy.
                    </p>
                </div>

                {/* Right Section (Form) */}
                <div className="w-1/2 p-[1rem] flex flex-col justify-center items-center">
                    <h2 className="text-center text-[2.5rem] font-[800] text-primary mb-8">SIGN UP</h2>
                    {/* Signup heading underline */}
                    <div class="h-[0.4rem] w-[6rem] top-[4.5rem] rounded-[10px] left-[41.5rem] bg-primary absolute"></div>
                    <form className="space-y-6">
                        {/* Full Name */}
                        <div className="space-y-3">
                            <div className="relative w-[20rem]">
                                <input
                                    id="name"
                                    type="text"
                                    placeholder="FULL NAME"
                                    className="peer py-3 pe-0 ps-8 block w-full bg-transparent border-t-transparent border-b-2 border-x-transparent border-b-gray-200 text-sm focus:border-t-transparent focus:border-x-transparent focus:border-b-blue-500 focus:ring-0 disabled:opacity-50 disabled:pointer-events-none dark:border-b-neutral-700 dark:text-neutral-400 dark:placeholder-neutral-500 dark:focus:ring-neutral-600 dark:focus:border-b-neutral-600"
                                />
                                <div className="absolute inset-y-0 start-0 flex items-center pointer-events-none ps-2 peer-disabled:opacity-50 peer-disabled:pointer-events-none">
                                    <svg
                                        className="shrink-0 size-4 text-gray-500 dark:text-neutral-500"
                                        xmlns="http://www.w3.org/2000/svg"
                                        width="24"
                                        height="24"
                                        viewBox="0 0 24 24"
                                        fill="none"
                                        stroke="currentColor"
                                        strokeWidth="2"
                                        strokeLinecap="round"
                                        strokeLinejoin="round"
                                    >
                                        <path d="M19 21v-2a4 4 0 0 0-4-4H9a4 4 0 0 0-4 4v2"></path>
                                        <circle cx="12" cy="7" r="4"></circle>
                                    </svg>
                                </div>
                            </div>

                            {/* Email */}
                            <div className="relative w-[20rem]">
                                <input
                                    id="email"
                                    type="email"
                                    placeholder="EMAIL"
                                    className="peer py-3 pe-0 ps-8 block w-full bg-transparent border-t-transparent border-b-2 border-x-transparent border-b-gray-200 text-sm focus:border-t-transparent focus:border-x-transparent focus:border-b-blue-500 focus:ring-0 disabled:opacity-50 disabled:pointer-events-none dark:border-b-neutral-700 dark:text-neutral-400 dark:placeholder-neutral-500 dark:focus:ring-neutral-600 dark:focus:border-b-neutral-600"
                                />
                                <div className="absolute inset-y-0 start-0 flex items-center pointer-events-none ps-2 peer-disabled:opacity-50 peer-disabled:pointer-events-none">
                                    <svg
                                        className="shrink-0 size-4 text-gray-500 dark:text-neutral-500"
                                        xmlns="http://www.w3.org/2000/svg"
                                        width="24"
                                        height="24"
                                        viewBox="0 0 24 24"
                                        fill="none"
                                        stroke="currentColor"
                                        strokeWidth="2"
                                        strokeLinecap="round"
                                        strokeLinejoin="round"
                                    >
                                        <path d="M16 12V8a4 4 0 0 0-8 0v4H6a2 2 0 0 0-2 2v4a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2v-4a2 2 0 0 0-2-2h-2z"></path>
                                    </svg>
                                </div>
                            </div>

                            {/* Phone */}
                            <div className="relative w-[20rem]">
                                <input
                                    id="phone"
                                    type="tel"
                                    placeholder="PHONE"
                                    className="peer py-3 pe-0 ps-8 block w-full bg-transparent border-t-transparent border-b-2 border-x-transparent border-b-gray-200 text-sm focus:border-t-transparent focus:border-x-transparent focus:border-b-blue-500 focus:ring-0 disabled:opacity-50 disabled:pointer-events-none dark:border-b-neutral-700 dark:text-neutral-400 dark:placeholder-neutral-500 dark:focus:ring-neutral-600 dark:focus:border-b-neutral-600"
                                />
                                <div className="absolute inset-y-0 start-0 flex items-center pointer-events-none ps-2 peer-disabled:opacity-50 peer-disabled:pointer-events-none">
                                    <svg
                                        className="shrink-0 size-4 text-gray-500 dark:text-neutral-500"
                                        xmlns="http://www.w3.org/2000/svg"
                                        width="24"
                                        height="24"
                                        viewBox="0 0 24 24"
                                        fill="none"
                                        stroke="currentColor"
                                        strokeWidth="2"
                                        strokeLinecap="round"
                                        strokeLinejoin="round"
                                    >
                                        <path d="M22 12H2"></path>
                                        <polyline points="16 6 22 12 16 18"></polyline>
                                    </svg>
                                </div>
                            </div>

                            {/* Password */}
                            <div className="relative w-[20rem]">
                                <input
                                    id="password"
                                    type="password"
                                    placeholder="PASSWORD"
                                    className="peer py-3 pe-0 ps-8 block w-full bg-transparent border-t-transparent border-b-2 border-x-transparent border-b-gray-200 text-sm focus:border-t-transparent focus:border-x-transparent focus:border-b-blue-500 focus:ring-0 disabled:opacity-50 disabled:pointer-events-none dark:border-b-neutral-700 dark:text-neutral-400 dark:placeholder-neutral-500 dark:focus:ring-neutral-600 dark:focus:border-b-neutral-600"
                                />
                                <div className="absolute inset-y-0 start-0 flex items-center pointer-events-none ps-2 peer-disabled:opacity-50 peer-disabled:pointer-events-none">
                                    <svg
                                        className="shrink-0 size-4 text-gray-500 dark:text-neutral-500"
                                        xmlns="http://www.w3.org/2000/svg"
                                        width="24"
                                        height="24"
                                        viewBox="0 0 24 24"
                                        fill="none"
                                        stroke="currentColor"
                                        strokeWidth="2"
                                        strokeLinecap="round"
                                        strokeLinejoin="round"
                                    >
                                        <path d="M6 12V8a6 6 0 0 1 12 0v4"></path>
                                        <rect x="6" y="12" width="12" height="8" rx="2"></rect>
                                    </svg>
                                </div>
                            </div>

                            {/* Confirm Password */}
                            <div className="relative w-[20rem]">
                                <input
                                    id="confirm-password"
                                    type="password"
                                    placeholder="CONFIRM PASSWORD"
                                    className="peer py-3 pe-0 ps-8 block w-full bg-transparent border-t-transparent border-b-2 border-x-transparent border-b-gray-200 text-sm focus:border-t-transparent focus:border-x-transparent focus:border-b-blue-500 focus:ring-0 disabled:opacity-50 disabled:pointer-events-none dark:border-b-neutral-700 dark:text-neutral-400 dark:placeholder-neutral-500 dark:focus:ring-neutral-600 dark:focus:border-b-neutral-600"
                                />
                                <div className="absolute inset-y-0 start-0 flex items-center pointer-events-none ps-2 peer-disabled:opacity-50 peer-disabled:pointer-events-none">
                                    <svg
                                        className="shrink-0 size-4 text-gray-500 dark:text-neutral-500"
                                        xmlns="http://www.w3.org/2000/svg"
                                        width="24"
                                        height="24"
                                        viewBox="0 0 24 24"
                                        fill="none"
                                        stroke="currentColor"
                                        strokeWidth="2"
                                        strokeLinecap="round"
                                        strokeLinejoin="round"
                                    >
                                        <path d="M12 22v-2a4 4 0 0 1 4-4h1a4 4 0 0 1 4 4v2"></path>
                                        <circle cx="12" cy="7" r="4"></circle>
                                    </svg>
                                </div>
                            </div>
                        </div>

                        {/* Submit Button */}
                        <div>
                            <button
                                type="submit"
                                className="w-full bg-primarybtn hover:bg-primary text-white py-3 px-4 rounded-full transition duration-300"
                            >
                                SUBMIT
                            </button>
                        </div>

                        {/* Login Prompt */}
                        <div className="mt-6 text-center text-sm text-gray-600 uppercase">
                            Already have an account?{" "}
                            <a href="/login" className="text-primary font-bold hover:underline">
                                Login
                            </a>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    );
};

export default Signup;

**Comment by iamsohelx** [comment]
@Anuj3553 Thank you

**Comment by iamsohelx** [comment]
@Anuj3553 Yeah sure brother, could you please give this level 2

**Comment by iamsohelx** [comment]
@Anuj3553 is it good or should i add something?
![LoginPage](https://github.com/user-attachments/assets/095b293c-148e-4b33-9b6a-dbfb50f16a1b)

**Comment by Anuj3553** [comment]
Can you change color - blue as our website color pallate and under welcome text please give more text as well as give more width...please provide the video of your work.

**Comment by Anuj3553** [comment]
> @Anuj3553 Yeah sure brother, could you please give this level 2

No i can provide only label - level1 for this work .

**Comment by iamsohelx** [comment]
> Can you change color - blue as our website color pallate and under welcome text please give more text as well as give more width...please provide the video of your work.

Yeah sure

**Comment by iamsohelx** [comment]
@Anuj3553 Now brother? 
## Video 
Brother I can not send you the video here because, it only can send files less than 10 mb, give me your WhatsApp number I will send then

**Comment by Anuj3553** [comment]
> @Anuj3553 Now brother?
> 
> ## Video
> Brother I can not send you the video here because, it only can send files less than 10 mb, give me your WhatsApp number I will send then

8081718102

**Comment by iamsohelx** [comment]
> > @Anuj3553 Now brother?
> > ## Video
> > Brother I can not send you the video here because, it only can send files less than 10 mb, give me your WhatsApp number I will send then
> 
> 8081718102

Done

**Comment by Anuj3553** [comment]
Well done, @iamsohelx, on completing the issue! 🎉
Your efforts are truly valued. Keep up the great work, and continue contributing your talents!

**Comment by Anuj3553** [comment]
Hyy @iamsohelx, Can you do star mark this repo?

**Comment by iamsohelx** [comment]
@Anuj3553 Yeah sure brother

**Comment by iamsohelx** [comment]
> Hyy @iamsohelx, Can you do star mark this repo?

Done ✅
