### ISSUE TITLE
Github actions for more connectivity!

### ISSUE THREAD

**Issue by smog-root** [Bitbox-Connect/Bitbox#192]
**We can implement github workflows for the following things:**

1. Auto comment on issue **Closed** and **Opened** (already implemented in you'r repo)!!
2. Auto comment on **PR mergs** (already implemented in you'r repo)!!
3. Auto comment on **PR raises** ( i can work on this)?

Using this workflows makes you'r repo more interactive ! @Anuj3553 

_**i'm expecting a level2 (or) level3 with gssoc-ext and hacktoberfest-accepted label**_

**Comment by Anuj3553** [comment]
Hyy @smog-root, I'm assigning this issue to you.
