### ISSUE TITLE
[Feature Request]: Addition of toggle password feature in the signup page.

### ISSUE THREAD

**Issue by ShivanshPlays** [Bitbox-Connect/Bitbox#195]
### Is there an existing feature request for this?

- [X] I have searched the existing feature requests

### Describe the feature you would like to request

To improve usability and user experience, I propose adding a **password visibility toggle** (e.g., an eye icon) to the password fields on both the registration and login pages. This will allow users to toggle between hidden and visible password states.

### What problem does this feature solve?

Currently, the password input fields on both the **registration** and **login** pages hide the password by default. While this enhances security, it can cause usability issues, leading to failed login attempts or registration frustrations.

### Confirmation

- [X] I have read the Bitbox Contributing Guidelines
- [X] I am a GSSOC-EXT contributor
- [X] I am a HACKTOBERFEST contributor
- [X] I have starred the Bitbox repository
- [X] I would like to help implement this feature

**Comment by ShivanshPlays** [comment]
![Screenshot 2024-10-21 230228](https://github.com/user-attachments/assets/a6b23dec-a889-49d2-8d73-7079681f4f91)

**Comment by Anuj3553** [comment]
Hyy @ShivanshPlays, I'm assigning this issue to you.

**Comment by Anuj3553** [comment]
Can you give star to this repo?

**Comment by ShivanshPlays** [comment]
@Anuj3553 sure
