### ISSUE TITLE
cards overflow and too much into border side

### ISSUE THREAD

**Issue by anshxika** [Bitbox-Connect/Bitbox#199]
## Summary

on the home page , all the cards are too much into screen border , makes it look like they are stretched or oversized 
the cards under what we work section are overflowing , the title are now contained in the card boundary

## Details

i will be aligning the elements to a proper standard side from getting into the borders and will fix the texts/titles in the cards as per spacing 

## Relevant Context
as you can see below , the cards are almost touching the boundaries and it doesn't look elegant

![Screenshot 2024-10-22 063706](https://github.com/user-attachments/assets/4200d857-df0a-44aa-8b42-f9a66a24e8b8)
and here the title coming out of the card:

![Screenshot 2024-10-22 063748](https://github.com/user-attachments/assets/0b5e88c1-1ca3-48d1-9c41-64269d9146e0)

## Additional Notes

@Anuj3553 please assign me this issue and let me fix it, i'll do it as quick as possible , under gssoc and hacktoberfest , thanks

**Comment by Anuj3553** [comment]
Already Fixed the issue @anshxika

**Comment by Anuj3553** [comment]
Can you give star to this repo?

**Comment by Harshit7492** [comment]
Thanks for your support and interest  @anshxika
