### ISSUE TITLE
Issue:Redesign the Login and Signup page

### ISSUE THREAD

**Issue by Hh440** [Bitbox-Connect/Bitbox#2]
Login and Signup page are not looking good.
![Screenshot from 2024-10-03 18-05-14](https://github.com/user-attachments/assets/9eaf8f25-aa40-46e1-ac4a-229e74b2e2db)
![Screenshot from 2024-10-03 18-05-21](https://github.com/user-attachments/assets/def07a21-7d9c-4322-823d-5672e58c78e1)

this is how it look like this now 

this is how i want to create it
![Screenshot from 2024-10-03 18-07-55](https://github.com/user-attachments/assets/e1e3fa10-468c-47d3-ac9b-e6a2f9aa4731)
![Screenshot from 2024-10-03 18-08-08](https://github.com/user-attachments/assets/067ae5e3-e53d-4d18-829b-68346c772cf6)

**Comment by Hh440** [comment]
Please can you also add hacktoberfest label

**Comment by Hh440** [comment]
i am more comforatblw using tailwind css .if it's ok with you can i use tailwind css

**Comment by Anuj3553** [comment]
> Please can you also add hacktoberfest label

Okk I'll do it.

**Comment by Anuj3553** [comment]
> i am more comforatblw using tailwind css .if it's ok with you can i use tailwind css

Our project is built on Bootstrap. If you can use Bootstrap, that would be great. However, if you prefer to use Tailwind and Bootstrap together without affecting each other's styling, that would be even better.

**Comment by Harshit7492** [comment]
@Hh440  Can you also attach authentication in this page

**Comment by Anuj3553** [comment]
> i am more comforatblw using tailwind css .if it's ok with you can i use tailwind css
If you want to start working, we will create a new branch for you so you can work seamlessly. We will check your branch to ensure it is compatible, and then we will push your code.

**Comment by Anuj3553** [comment]
> Please can you also add hacktoberfest label

We will give you a label after reviewing your work, and then we will assign the Hacktoberfest label.

**Comment by Hh440** [comment]
@Anuj3553 i have completed creating the login and signup but during this their is a slight problem i am facing somehow navigation bar content is not being dispalyed. since your are more familiar with your code so please take a look at the code. I will create a PR so please look into it

**Comment by Anuj3553** [comment]
Hyy @Hh440, 

Can i close this issue.

**Comment by Hh440** [comment]
Sure

**Comment by Hh440** [comment]
Sure

**Comment by Anuj3553** [comment]
Congratulations to the @Hh440  for successfully completing the issue: Redesign the Login and Signup page! Your efforts in improving the user experience are greatly appreciated.

**Comment by Hh440** [comment]
please add the hactoberfest label to PR it was not added

**Comment by Anuj3553** [comment]
Thank you, @Hh440, for letting me know about your issue.
Keep contributing! Wishing you all the best on your journey!

**Comment by Anuj3553** [comment]
Can you so star mark this repo?

**Comment by Hh440** [comment]
I already did
