### ISSUE TITLE
[Feature Request]: change the discussion page to dark mode

### ISSUE THREAD

**Issue by AE-Hertz** [Bitbox-Connect/Bitbox#200]
### Is there an existing feature request for this?

- [X] I have searched the existing feature requests

### Describe the feature you would like to request

change the dark mode effect in discussion page

### What problem does this feature solve?

the discussion page is too bright in dark mode , i will fix this.
![Screenshot 2024-10-22 111919](https://github.com/user-attachments/assets/38f80944-bdef-4f8f-9138-dbf69f676d22)

### Confirmation

- [X] I have read the Bitbox Contributing Guidelines
- [X] I am a GSSOC-EXT contributor
- [X] I am a HACKTOBERFEST contributor
- [X] I have starred the Bitbox repository
- [X] I would like to help implement this feature

**Comment by AE-Hertz** [comment]
assign me this under hacktoberfest and gssoc-ext

**Comment by Anuj3553** [comment]
Hyy @AE-Hertz, I'm assining this issue to you.

**Comment by AE-Hertz** [comment]
For sure, I liked your work tbh.
