### ISSUE TITLE
Update twitter logo.

### ISSUE THREAD

**Issue by Sandigupta** [Bitbox-Connect/Bitbox#201]
## Summary

Let me update the twitter logo with new logo. It will improve the overall user experience and reduce confusion among new users.

## Details
![Screenshot 2024-10-22 112503](https://github.com/user-attachments/assets/3cef06e0-5c8c-466e-9fe7-037757163db5)

**Comment by Anuj3553** [comment]
Hyy @Sandigupta, Already given this issue to someone.

**Comment by Anuj3553** [comment]
Can you give star to this repo?

**Comment by Harshit7492** [comment]
Thank you for your Support @Sandigupta
