### ISSUE TITLE
[Feature Request]: Ensure Protection to all the routes of the website such about us and discussion

### ISSUE THREAD

**Issue by 2004vivek** [Bitbox-Connect/Bitbox#202]
### Is there an existing feature request for this?

- [X] I have searched the existing feature requests

### Describe the feature you would like to request

I observed i am able to access the about us page and discussion page without login to the website which make insecure and increase the chance of malicious attack to the website

### What problem does this feature solve?

I feel that if there is sensitive information of the user in the particular page then it can be easily acccessed by unauthorised person and they can manipulate that information there in the website
![image](https://github.com/user-attachments/assets/48f3274f-3b90-4b7d-8586-8cfca662d1df)

### Confirmation

- [X] I have read the Bitbox Contributing Guidelines
- [X] I am a GSSOC-EXT contributor
- [X] I am a HACKTOBERFEST contributor
- [X] I have starred the Bitbox repository
- [X] I would like to help implement this feature

**Comment by Anuj3553** [comment]
Hyy @2004vivek, I'm assigning this issue to you.

**Comment by Anuj3553** [comment]
Can you give star to the repo?
