### ISSUE TITLE
[Bug]: website glitching on community page and no navbar on login and signup pages.

### ISSUE THREAD

**Issue by ShivanshPlays** [Bitbox-Connect/Bitbox#206]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Hi @Anuj3553 bro, I request you to please go through the PRS you are merging.

First of all the website on the deployment and on the local server are slightly different.

Second, I noticed that someone raised a PR for revamping signup and login components and they messed up the whole layout, right now the navbar is not even getting displayed in the login signup page.

I can solve all these issues under a lvl3 if you let me.

### Expected behavior

Proper UI

### Add screenshots (if applicable)

![image](https://github.com/user-attachments/assets/d6df6e47-65c8-4b05-8bc2-3ba4e6467fa8)

![image](https://github.com/user-attachments/assets/ccb205da-5ff4-4272-91dd-df8b22fca571)

![image](https://github.com/user-attachments/assets/00c21812-febb-471f-9f6c-63c8eac23f02)

### Confirmation

- [X] I have read the Bitbox Contributing Guidelines
- [X] I am a GSSOC-EXT contributor
- [X] I am a HACKTOBERFEST contributor
- [X] I have starred the Bitbox repository

**Comment by Anuj3553** [comment]
Hyy @ShivanshPlays, I'm assigning this issue to you.
