### ISSUE TITLE
adding code_of conduct.md

### ISSUE THREAD

**Issue by jyothimanoj12** [Bitbox-Connect/Bitbox#21]
A Code of Conduct ensures inclusivity, prevents harassment, clarifies behavioral expectations, encourages professionalism, and fosters a safe, welcoming community for contributors.

plz assisn me this issue under gsoc-extended , level 1 , hacktoberfest-accepted tag

**Comment by Anuj3553** [comment]
Hi @jyothimanoj12,

You can proceed with this issue. I've assigned it to you under the GSOC-Extended, Level 1, and Hacktoberfest-Accepted tags.

**Comment by Anuj3553** [comment]
Hyy @jyothimanoj12, Can you do star mark this repo?

**Comment by jyothimanoj12** [comment]
Done
