### ISSUE TITLE
[Feature Request]: Add testimonial for ganning user trust

### ISSUE THREAD

**Issue by Sawan-Kushwah** [Bitbox-Connect/Bitbox#220]
### Is there an existing feature request for this?

- [X] I have searched the existing feature requests

### Describe the feature you would like to request

By adding stronger testimonials, we can build user trust, improve credibility, and significantly enhance the overall experience on our platform

### What problem does this feature solve?

![Screenshot 2024-10-18 191732](https://github.com/user-attachments/assets/52a65bb1-cc7d-49ce-81b1-77586772c118)

Something like this i can redesign it according to website theme and make it more beautiful
on clicking on the arrow cards slide with an animation with create great user impact 

### Confirmation

- [X] I have read the Bitbox Contributing Guidelines
- [X] I am a GSSOC-EXT contributor
- [X] I am a HACKTOBERFEST contributor
- [X] I have starred the Bitbox repository
- [X] I would like to help implement this feature

**Comment by Anuj3553** [comment]
Hyy @Sawan-Kushwah, I'm assigning this issue to you.
