### ISSUE TITLE
[Feature Request]: Backend for contact form 

### ISSUE THREAD

**Issue by Sawan-Kushwah** [Bitbox-Connect/Bitbox#221]
### Is there an existing feature request for this?

- [X] I have searched the existing feature requests

### Describe the feature you would like to request

i can build contact form backend api 

### What problem does this feature solve?

i will take care of folder structure 

### Confirmation

- [X] I have read the Bitbox Contributing Guidelines
- [X] I am a GSSOC-EXT contributor
- [X] I am a HACKTOBERFEST contributor
- [X] I have starred the Bitbox repository
- [X] I would like to help implement this feature

**Comment by Anuj3553** [comment]
Can you give star to this repo?

**Comment by Sawan-Kushwah** [comment]
@Anuj3553 of course why not! ☺️

**Comment by Sawan-Kushwah** [comment]
@Anuj3553 I will raise all pr by tomorrow!
Just a request please merge them ASAP as you know rank is important in GSSOC
If some changes is there I am ready to do ☺️👍

**Comment by Anuj3553** [comment]
> @Anuj3553 I will raise all pr by tomorrow! Just a request please merge them ASAP as you know rank is important in GSSOC If some changes is there I am ready to do ☺️👍

Okk :)
