### ISSUE TITLE
[Feature Request]: Add beautiful animation through out the website 

### ISSUE THREAD

**Issue by Sawan-Kushwah** [Bitbox-Connect/Bitbox#224]
### Is there an existing feature request for this?

- [X] I have searched the existing feature requests

### Describe the feature you would like to request

i can implement the animation through out the website for better user experience 

### What problem does this feature solve?

using AOS or Animated animation 

### Confirmation

- [X] I have read the Bitbox Contributing Guidelines
- [X] I am a GSSOC-EXT contributor
- [X] I am a HACKTOBERFEST contributor
- [X] I have starred the Bitbox repository
- [X] I would like to help implement this feature

**Comment by Harshit7492** [comment]
Please share some screenshots for this @Sawan-Kushwah

**Comment by Sawan-Kushwah** [comment]
https://github.com/user-attachments/assets/9e270e95-1340-4d2a-b0d0-72fa2942c2b2
@Harshit7492 
Sample video of animation 
i have added this on a website 
Please watch it onces

**Comment by Anuj3553** [comment]
Hyy @Sawan-Kushwah,  I'm assigning this issue to you.

**Comment by Anuj3553** [comment]
Can you give star to this repo?

**Comment by Sawan-Kushwah** [comment]
@Anuj3553 i already star this repo !! seriously one of the best repo i have ever worked as project mentor are very active and supportive !

**Comment by Anuj3553** [comment]
> @Anuj3553 i already star this repo !! seriously one of the best repo i have ever worked as project mentor are very active and supportive !

Thankyou for your feedback. We are looking forward to you in any problem :).
