### ISSUE TITLE
[Bug]: Community page glitching

### ISSUE THREAD

**Issue by govindbairi** [Bitbox-Connect/Bitbox#226]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

https://github.com/user-attachments/assets/92ea0aca-063f-4cb5-a449-c9ddc5a75828

The community page experiences intermittent glitching, causing  elements to render improperly and affecting user experience.

### Expected behavior

Smooth Loading: The community page should load quickly and seamlessly, displaying all content without noticeable delays or interruptions.

### Add screenshots (if applicable)

https://github.com/user-attachments/assets/8de00738-8a2a-4a5d-bec9-fbf436ed60f8

### Confirmation

- [X] I have read the Bitbox Contributing Guidelines
- [X] I am a GSSOC-EXT contributor
- [ ] I am a HACKTOBERFEST contributor
- [X] I have starred the Bitbox repository

**Comment by Harshit7492** [comment]
Sorry @govindbairi you fork or cloned wrong repo. Try this  https://github.com/Bitbox-Connect/Bitbox
