### ISSUE TITLE
ADD Blog page to the website 

### ISSUE THREAD

**Issue by shubhagarwal1** [Bitbox-Connect/Bitbox#228]
<img width="1426" alt="image" src="https://github.com/user-attachments/assets/3d138437-6a1b-4f85-a92b-1c8322e0f94b">

**Comment by Harshit7492** [comment]
Hyy @shubhagarwal1 please share some screenshots for blog

**Comment by shubhagarwal1** [comment]
> Hyy @shubhagarwal1 please share some screenshots for blog
Hey @Harshit7492 here is the ref ss, if you have any design changes please let me know, also please assign me this task 
<img width="1414" alt="Screenshot 2024-10-24 at 12 57 37 PM" src="https://github.com/user-attachments/assets/1c513684-6c70-4d94-88b0-3be3c1647fde">

**Comment by Anuj3553** [comment]
Hyy @shubhagarwal1, I'm assigning this issue to you.

**Comment by Anuj3553** [comment]
Can you give star to this repo?

**Comment by shubhagarwal1** [comment]
> Can you give star to this repo?

sure @Anuj3553, thankyou for the opportunity.
