### ISSUE TITLE
Improve Discussion Page Chatbox and message styling [MODERN DESIGN IMPLEMENTATION]

### ISSUE THREAD

**Issue by shubhagarwal1** [Bitbox-Connect/Bitbox#229]
- Open a dedicated modal on landing page to take input for the user name 
- improve chat box make it more precise 
- changing backgroung image to light so that main focus could be on texts 
- changing theme of the page

**Comment by Harshit7492** [comment]
Hyy @shubhagarwal1 Please share some visuals here also

**Comment by shubhagarwal1** [comment]
<img width="228" alt="Screenshot 2024-10-24 at 1 01 12 PM" src="https://github.com/user-attachments/assets/49507486-4ff7-4a1d-b426-8544bb937406">
Hey @Harshit7492 please add your view to it also, please assign me this task 
Not exactly like this but design would be same
