### ISSUE TITLE
[Feature Request]: Adding a subscribe to newsletter option in footer

### ISSUE THREAD

**Issue by VinayLodhi1712** [Bitbox-Connect/Bitbox#245]
### Is there an existing feature request for this?

- [X] I have searched the existing feature requests

### Describe the feature you would like to request

Adding a subscribe to newsletter option in backend frontend both part

### What problem does this feature solve?

To email them the recent updates they can subscribe the newsletter.

### Confirmation

- [X] I have read the Bitbox Contributing Guidelines
- [X] I am a GSSOC-EXT contributor
- [X] I am a HACKTOBERFEST contributor
- [X] I have starred the Bitbox repository
- [X] I would like to help implement this feature

**Comment by Anuj3553** [comment]
Hyy @VinayLodhi1712, I'm assigning this issue to you.

**Comment by Anuj3553** [comment]
Can you give star to this repo?

**Comment by VinayLodhi1712** [comment]
yeah sure!

**Comment by Anuj3553** [comment]
> yeah sure! but i am making newsletter frontend and backend from storing email in backend to making api and using nodemailer and making frontend for it and normally other project admin give level 3 for it and you are giving just level 3 so plz @Anuj3553 sir can you increase its level it will help me a lot.

Done 👍
