### ISSUE TITLE
[Feature Request]: Adding a Star to Github Repo button and making visitor count show dynamically with good UI

### ISSUE THREAD

**Issue by VinayLodhi1712** [Bitbox-Connect/Bitbox#253]
### Is there an existing feature request for this?

- [X] I have searched the existing feature requests

### Describe the feature you would like to request

[Feature Request]: Adding a Star to Github Repo button and making visitor count show dynamically with good UI. Like this-

![visitor4](https://github.com/user-attachments/assets/ba3c9566-3f72-4761-ae93-9443441c1fd5)

it will look like -
![visiting](https://github.com/user-attachments/assets/f4ab95b1-8abd-4087-94fe-8905a8713f21)

### What problem does this feature solve?

Your visitors count is not dynamically it is using local storage which is  not good user experience.
And there is no star to github repo button in it so i will add it also in footer.

### Confirmation

- [X] I have read the Bitbox Contributing Guidelines
- [X] I am a GSSOC-EXT contributor
- [X] I am a HACKTOBERFEST contributor
- [X] I have starred the Bitbox repository
- [X] I would like to help implement this feature

**Comment by Anuj3553** [comment]
Hyy @VinayLodhi1712, I'm assigning issue to you.

**Comment by Anuj3553** [comment]
Can you give star to this repo?

**Comment by VinayLodhi1712** [comment]
already done
