### ISSUE TITLE
[Bug]: Back to top button

### ISSUE THREAD

**Issue by Jordian0** [Bitbox-Connect/Bitbox#256]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Back to top button is very laggy and slow

### Expected behavior

It should be smooth and fast.

### Add screenshots (if applicable)

https://github.com/user-attachments/assets/dec5a02e-5739-44fb-8922-1605b4e324a6

### Confirmation

- [X] I have read the Bitbox Contributing Guidelines
- [X] I am a GSSOC-EXT contributor
- [X] I am a HACKTOBERFEST contributor
- [X] I have starred the Bitbox repository

**Comment by Anuj3553** [comment]
Hyy @Jordian0, I'm assigning this issue to you.

**Comment by Anuj3553** [comment]
Can you give star to this repo?
