### ISSUE TITLE
Enhance our contributor page to look something cool

### ISSUE THREAD

**Issue by Sawan-Kushwah** [Bitbox-Connect/Bitbox#270]
![image](https://github.com/user-attachments/assets/526f3796-002c-42e8-ae43-29268ec2d176)

as you can see its not looking good 
i can make it look something like this 

![image](https://github.com/user-attachments/assets/d6034136-70f8-4cc6-a9d7-9e430f7df79c)
![image](https://github.com/user-attachments/assets/7513b2c0-2eb3-4d97-9f57-12bb69982f38)

this design is created by me !!

**Comment by Anuj3553** [comment]
Yes its good but not matching to our website color pallate and you are not working on react instead of you are done the work in html, css. For next mention the tech stack otherwise i will decrease your levels.

**Comment by Sawan-Kushwah** [comment]
@Anuj3553  i will align its css according to our website theme !!

**Comment by Sawan-Kushwah** [comment]
@Anuj3553 i am sorry for this if i miss match tech stack i will take care of it next time !

**Comment by Anuj3553** [comment]
> @Anuj3553 i will align its css according to our website theme !!

Ohkk I'm assigning this issue to you
