### ISSUE TITLE
[Custom]: Remove Toast Notification on Theme Change

### ISSUE THREAD

**Issue by AnushkaChouhan25** [Bitbox-Connect/Bitbox#274]
## Summary
I can remove unnecessary alert messages that appear when switching themes to provide a smoother user experience.

## Expected behaviour
Theme changes should occur seamlessly without toast notifications interrupting the flow.

## Relevant Context

![image](https://github.com/user-attachments/assets/1821c565-bf4b-4cbe-936a-da3b7c714fd4)## Additional Notes

**Comment by Anuj3553** [comment]
Hyy @AnushkaChouhan25, I'm assigning this issue to you.

**Comment by AnushkaChouhan25** [comment]
Thank you @Anuj3553
