### ISSUE TITLE
[Custom]: Add License Section to README.md✨

### ISSUE THREAD

**Issue by AnushkaChouhan25** [Bitbox-Connect/Bitbox#280]
## Summary
The README.md file is missing a license section, which is essential for clarifying the usage rights and permissions for the project.

## Details
 The README.md should include a clear license section specifying the type of license (e.g., MIT) and the associated terms.

![image](https://github.com/user-attachments/assets/2388b02e-38bc-4417-9b2a-7d3e7bcd8daa)

**Comment by Anuj3553** [comment]
Hyy @AnushkaChouhan25, I'm assigning this issue to you.

**Comment by Anuj3553** [comment]
Can you give star to this repo?
