### ISSUE TITLE
Enhance the ui of boxes on home page 

### ISSUE THREAD

**Issue by Sawan-Kushwah** [Bitbox-Connect/Bitbox#287]
![image](https://github.com/user-attachments/assets/2be9123f-15ea-4e9f-bc0f-566f4ad9812a)

enhance the ui of this boxes and add good hover effect
as home page is our first impression it should look the best !!! 

i can do this please assign me !!

**Comment by Sawan-Kushwah** [comment]
@Anuj3553 currently i dont have any sample but i assure you that it will be better from previous

**Comment by Anuj3553** [comment]
I think its good for now but if you have sample then i'm fully satisfied for your proposal.

**Comment by Sawan-Kushwah** [comment]
@Anuj3553 here is the sample !!
if changes required in ui i am ready to do 


https://github.com/user-attachments/assets/73f366a4-d966-4d21-b9f5-94ff25351c91

**Comment by Anuj3553** [comment]
Hyy @Sawan-Kushwah, I'm assigning this issue to you.
