### ISSUE TITLE
[Bug]: On writing the email its not showing the mail

### ISSUE THREAD

**Issue by Sawan-Kushwah** [Bitbox-Connect/Bitbox#288]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

![image](https://github.com/user-attachments/assets/7c4788d7-c796-45be-ba07-1c8fe1891e85)

when i enter my email here its doesnot show anything

### Expected behavior

![image](https://github.com/user-attachments/assets/a230c86b-fea0-404f-8a9f-1d38ecac151a)

### On which device or platform are you experiencing this bug?

Chrome

### Confirmation

- [X] I have read the Bitbox Contributing Guidelines
- [X] I am a GSSOC-EXT contributor
- [X] I am a HACKTOBERFEST contributor
- [X] I have starred the Bitbox repository

**Comment by Anuj3553** [comment]
Hyy @Sawan-Kushwah, I'm assigning this issue to you.
