### ISSUE TITLE
enhance ui of privacy policy

### ISSUE THREAD

**Issue by Sawan-Kushwah** [Bitbox-Connect/Bitbox#289]
![Uploading image.png…]()

as you can see its not looking its fully text base its ui should be enhance

**Comment by Anuj3553** [comment]
Hyy @Sawan-Kushwah, Check again your image it not rendered.

**Comment by Sawan-Kushwah** [comment]
@Anuj3553 i update it but just a snippets of current ui of privacy policy page

**Comment by Anuj3553** [comment]
https://bitbox-in.netlify.app/termofuse 

Check this can you make like this?

**Comment by Sawan-Kushwah** [comment]
@Anuj3553 sure i can make it!
Please assign me
