### ISSUE TITLE
[Bug]: Nav bar text is hidden

### ISSUE THREAD

**Issue by Sawan-Kushwah** [Bitbox-Connect/Bitbox#290]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

![image](https://github.com/user-attachments/assets/27769bfd-5bf7-4b50-8658-0ac295b21509)

as you can see when i click on hamburger the text on the navbar is not visible

### Expected behavior

its should be visible

### On which device or platform are you experiencing this bug?

Chrome

### Confirmation

- [X] I have read the Bitbox Contributing Guidelines
- [X] I am a GSSOC-EXT contributor
- [X] I am a HACKTOBERFEST contributor
- [X] I have starred the Bitbox repository

**Comment by Anuj3553** [comment]
Hyy @Sawan-Kushwah, I'm assigning this issue to you.
