### ISSUE TITLE
[Feature Request]: Add not found block on blog page

### ISSUE THREAD

**Issue by Sawan-Kushwah** [Bitbox-Connect/Bitbox#291]
### Is there an existing feature request for this?

- [X] I have searched the existing feature requests

### Describe the feature you would like to request

![image](https://github.com/user-attachments/assets/80bcc99a-cfa0-4565-aed0-81ca592ee884)

when someone search and if queery doesn't found it should show not found block which enhancce the user experience 

### What problem does this feature solve?

i can build theme oriented not found block 

### Confirmation

- [X] I have read the Bitbox Contributing Guidelines
- [X] I am a GSSOC-EXT contributor
- [X] I am a HACKTOBERFEST contributor
- [X] I have starred the Bitbox repository
- [X] I would like to help implement this feature

**Comment by Anuj3553** [comment]
Hyy @Sawan-Kushwah, I'm assigning this issue to you.
