### ISSUE TITLE
Enhance ui of code of conduct page

### ISSUE THREAD

**Issue by Sawan-Kushwah** [Bitbox-Connect/Bitbox#292]
![image](https://github.com/user-attachments/assets/12717ae4-1910-43a1-a688-ccb46c8a51b9)

i can improve its styling to look more beautiful

**Comment by Anuj3553** [comment]
Give me some sample.

**Comment by Sawan-Kushwah** [comment]
@Anuj3553 currently i dont have any sample i can improve it and in PR i of i will put output image

**Comment by Anuj3553** [comment]
Hyy @Sawan-Kushwah, I'm assigning this issue to you.
