### ISSUE TITLE
[Bug]: Content is not visible 

### ISSUE THREAD

**Issue by AADESHak007** [Bitbox-Connect/Bitbox#310]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

In the footer section the main heading is not visible in the dark mode  
I think it is merging with the background color and it can be changed for better visibility 
It is same for every page of your website   .
I think i would be able to resolve  it  .
Please assign this issue to me  .

### Expected behavior

I want to change the color the footer when it is getting toggled between dark and light mode .

### Add screenshots (if applicable)

![Screenshot 2024-10-29 095720](https://github.com/user-attachments/assets/b08d812f-4455-444a-8879-0adc22620bc2)

### On which device or platform are you experiencing this bug?

Chrome

### Confirmation

- [X] I have read the Bitbox Contributing Guidelines
- [X] I am a GSSOC-EXT contributor
- [X] I am a HACKTOBERFEST contributor
- [X] I have starred the Bitbox repository

**Comment by Anuj3553** [comment]
Hyy @AADESHak007, I'm assigning this issue to you.
