### ISSUE TITLE
[Documentation] : Enhancement Of Contributing.md

### ISSUE THREAD

**Issue by milansamuel609** [Bitbox-Connect/Bitbox#311]
Wanted to do the following changes :-

1) Enhance the project structure
2) Add star our repository section
3) Add the project structure
4) Add need help with the basics section
5) Enhance the pull request steps section
6) Add additional method of contributing through GitHub desktop section
7) Add good coding practices section
8) Add the pull request rules section
9) Add the issue process section

It is really helpful and makes the contribution more easier for the contributors.

**Comment by Anuj3553** [comment]
Hyy @milansamuel609, I'm assigning this issue to you.

**Comment by milansamuel609** [comment]
> Hyy @milansamuel609, I'm assigning this issue to you.

Sure 👍. I will do it by today itself

**Comment by Anuj3553** [comment]
Can you give star to this repo?

**Comment by milansamuel609** [comment]
> Can you give star to this repo?

I have already starred this repository earlier. 🙂
