### ISSUE TITLE
Real Blog page where user can post there own blog 

### ISSUE THREAD

**Issue by Sawan-Kushwah** [Bitbox-Connect/Bitbox#312]
### Is there an existing feature request for this?

- [X] I have searched the existing feature requests

### Describe the feature you would like to request

![image](https://github.com/user-attachments/assets/b125c9a3-3625-43f5-a841-09497f33a7bd)

Added full functional blog page
You can create your own blog
you can read all blog

### What problem does this feature solve?

by this feature we get the real blog data of human where they share there own thoughts !! 
![image](https://github.com/user-attachments/assets/e45e4ac1-a150-4341-8e73-d59dd0a0badf)
i can redesign it according to website theme

here you can create your own blog 
i can do it with full backend integration !

### Confirmation

- [X] I have read the Bitbox Contributing Guidelines
- [X] I am a GSSOC-EXT contributor
- [X] I am a HACKTOBERFEST contributor
- [X] I have starred the Bitbox repository
- [X] I would like to help implement this feature

**Comment by Anuj3553** [comment]
Hyy @Sawan-Kushwah, I'm assigning this issue to you.
