### ISSUE TITLE
[Bug]: 🐞"Blog Page" Cards Text Not Visible in Dark Theme

### ISSUE THREAD

**Issue by AnushkaChouhan25** [Bitbox-Connect/Bitbox#316]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The text on blog page cards becomes invisible and hard to read in a dark theme. Update the text color to ensure proper visibility and alignment with the theme.

### Expected behavior

The text on blog page cards should be visible and readable in both light and dark themes, with colors aligned to the respective theme for a better user experience.

### Add screenshots (if applicable) 
![image](https://github.com/user-attachments/assets/26a1e751-2a86-4e09-8a22-2f18577292cd)

### Confirmation

- [X] I have read the Bitbox Contributing Guidelines
- [X] I am a GSSOC-EXT contributor
- [X] I am a HACKTOBERFEST contributor
- [X] I have starred the Bitbox repository

**Comment by Anuj3553** [comment]
Hyy @AnushkaChouhan25, I'm assigning this issue to you.
