### ISSUE TITLE
[Bug]: fix the overlapping of navbar and contact us heading

### ISSUE THREAD

**Issue by ananyag309** [Bitbox-Connect/Bitbox#323]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

fix this 

![image](https://github.com/user-attachments/assets/5e0006e1-6eee-4f29-8ab0-cf882a1057e2)

### Expected behavior

modify the ui

### Confirmation

- [X] I have read the Bitbox Contributing Guidelines
- [X] I am a GSSOC-EXT contributor
- [X] I am a HACKTOBERFEST contributor
- [X] I have starred the Bitbox repository

**Comment by IkkiOcean** [comment]
@Anuj3553 can I work on this issue as it seems inactive?

**Comment by Anuj3553** [comment]
> @Anuj3553 can I work on this issue as it seems inactive?

Hyy @IkkiOcean, You can work on this issue.
