### ISSUE TITLE
 Add Validation to contact us Message Field

### ISSUE THREAD

**Issue by ananyag309** [Bitbox-Connect/Bitbox#324]
Implement validation for the message field to ensure users enter at least 5 characters, disallowing single-character inputs. This will enhance form usability and improve user experience by guiding proper input length and simplifying the UI.

**Comment by Anuj3553** [comment]
Hyy @ananyag309 , I'm assigning this issue to you.

**Comment by ananyag309** [comment]
I will be submitting pr tomorrow
