### ISSUE TITLE
[Feature Request]: Create read more page for blog data fetched by backend

### ISSUE THREAD

**Issue by Sawan-Kushwah** [Bitbox-Connect/Bitbox#327]
### Is there an existing feature request for this?

- [X] I have searched the existing feature requests

### Describe the feature you would like to request

![image](https://github.com/user-attachments/assets/a1a8acc2-6484-4784-9b5c-343a67ed82e5)

### What problem does this feature solve?

when blog are too big it is not good to show all content on blog page 
if blog is big then turn cate it and there should be a read more page where we show full content of blog !!
this data has been fetched by BACKEND 

### Confirmation

- [X] I have read the Bitbox Contributing Guidelines
- [X] I am a GSSOC-EXT contributor
- [X] I am a HACKTOBERFEST contributor
- [X] I have starred the Bitbox repository
- [X] I would like to help implement this feature

**Comment by Anuj3553** [comment]
Hyy @Sawan-Kushwah, I'm assigning this issue to you.
