### ISSUE TITLE
[Bug]: Navbar in responsive mode not working correctly

### ISSUE THREAD

**Issue by VinayLodhi1712** [Bitbox-Connect/Bitbox#328]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

[Bug]: Navbar in responsive mode not working correctly

### Expected behavior

it should show and hide accoridinly and show on top but it showing in middle and after coming again to the full mode that navbar does not hide

### Add screenshots (if applicable)

![navbar issue](https://github.com/user-attachments/assets/a70a3180-5380-4906-aeb5-8101a0bc4f62)
![ba](https://github.com/user-attachments/assets/11725b66-b825-4024-a823-619af76cdc4d)

### Confirmation

- [X] I have read the Bitbox Contributing Guidelines
- [X] I am a GSSOC-EXT contributor
- [X] I am a HACKTOBERFEST contributor
- [X] I have starred the Bitbox repository

**Comment by Anuj3553** [comment]
Hyy @VinayLodhi1712, I'm assigning this issue to you.
