### ISSUE TITLE
[Bug]: Forgot password page sending mail to the email without checking it is already a user or not.

### ISSUE THREAD

**Issue by VinayLodhi1712** [Bitbox-Connect/Bitbox#329]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

[Bug]: Forgot password page sending mail to the email without checking it is already a user or not. It must check it is already a user in mongodb and then send the mail.

### Expected behavior

[Bug]: Forgot password page sending mail to the email without checking it is already a user or not. It must check it is already a user in mongodb and then send the mail.

### Add screenshots (if applicable)

https://github.com/user-attachments/assets/70faf5f3-2549-4b75-8edd-3f5ed9c1ddb0

### Confirmation

- [X] I have read the Bitbox Contributing Guidelines
- [X] I am a GSSOC-EXT contributor
- [X] I am a HACKTOBERFEST contributor
- [X] I have starred the Bitbox repository

**Comment by Anuj3553** [comment]
Hyy @VinayLodhi1712, I'm assigning this issue to you.
