### ISSUE TITLE
show open issue and what they contribute

### ISSUE THREAD

**Issue by Sawan-Kushwah** [Bitbox-Connect/Bitbox#336]
### Is there an existing feature request for this?

- [X] I have searched the existing feature requests

### Describe the feature you would like to request

If anyone wants to contribute, you can show them open issues.

On click contributor profile redirect to new page where you can show what they contribute to this project.

### What problem does this feature solve?

![image](https://github.com/user-attachments/assets/326a9f36-98f1-4401-973e-675e895412b9)

i will redesign it according to our website theme !!

### Confirmation

- [X] I have read the Bitbox Contributing Guidelines
- [X] I am a GSSOC-EXT contributor
- [X] I am a HACKTOBERFEST contributor
- [X] I have starred the Bitbox repository
- [X] I would like to help implement this feature

**Comment by Anuj3553** [comment]
Hyy @Sawan-Kushwah, I'm assigning this issue to you.
