### ISSUE TITLE
[ UI Improvement ] Making Footer Responsive.

### ISSUE THREAD

**Issue by subrataCS** [Bitbox-Connect/Bitbox#34]
I want to make the footer responsive for smaller screen size and improve the  UI  little-bit.
Kindly assign this issue to me under hactoberfest, gssoc-ext and relevant tags.

![image](https://github.com/user-attachments/assets/d3b09c7e-de48-46f4-9624-b503b7b2312e)

**Comment by Anuj3553** [comment]
Okk, @subrataCS  I'm assigning to you.

**Comment by Anuj3553** [comment]
Can you so star mark this repo?

**Comment by subrataCS** [comment]
Done
