### ISSUE TITLE
[Feature Request]: Implemeting otp functionality for login

### ISSUE THREAD

**Issue by Sourabh782** [Bitbox-Connect/Bitbox#344]
### Is there an existing feature request for this?

- [X] I have searched the existing feature requests

### Describe the feature you would like to request

implementing otp verification for login

### What problem does this feature solve?

it solves the problem of unauthorized login

### Confirmation

- [X] I have read the Bitbox Contributing Guidelines
- [X] I am a GSSOC-EXT contributor
- [X] I am a HACKTOBERFEST contributor
- [X] I have starred the Bitbox repository
- [X] I would like to help implement this feature

**Comment by Anuj3553** [comment]
Hyy @Sourabh782, I'm assigning this issue to you.

**Comment by Sourabh782** [comment]
> Hyy @Sourabh782, I'm assigning this issue to you.

Thanks working on it

**Comment by Anuj3553** [comment]
Can you give star to this repo?

**Comment by Sourabh782** [comment]
> Can you give star to this repo?

Sure👍👍

**Comment by Sourabh782** [comment]
@Anuj3553, can you help me with something? 
So i have imeplemented otp based backend, for frontend can you guide how should i implement?

option: 
1. user enter email and password, then user is redirected to otp screen
2. we give user option either to login with email, password or login with email and otp

can you tell which one is better?

**Comment by Sourabh782** [comment]
> > @Anuj3553, can you help me with something? So i have imeplemented otp based backend, for frontend can you guide how should i implement?
> > option:
> > 
> > 1. user enter email and password, then user is redirected to otp screen
> > 2. we give user option either to login with email, password or login with email and otp
> > 
> > can you tell which one is better?
> 
> We can give otp from user mobile number. Try to implement with firebase. It like optional user can login through email, password or mobile number.

Ohhkkk

**Comment by Sourabh782** [comment]
hello @Anuj3553, just wanted to confirm some things, do you have google cloud billing activated in your firebase account?

**Comment by Anuj3553** [comment]
> hello @Anuj3553, just wanted to confirm some things, do you have google cloud billing activated in your firebase account?

No i have not.

**Comment by Sourabh782** [comment]
> > hello @Anuj3553, just wanted to confirm some things, do you have google cloud billing activated in your firebase account?
> 
> No i have not.

actually i have implemented the code but for otp the firebase required cloud billing activated account

**Comment by Anuj3553** [comment]
> > > hello @Anuj3553, just wanted to confirm some things, do you have google cloud billing activated in your firebase account?
> > 
> > 
> > No i have not.
> 
> actually i have implemented the code for frontend and firebase otp verification but for otp the firebase required cloud billing activated account

Okk

**Comment by Anuj3553** [comment]
Can you try with twillio as a trial account.

**Comment by Sourabh782** [comment]
> Can you try with twillio as a trial account.

Okk working on it👍👍
