### ISSUE TITLE
[Feature Request]: Adding a new page to display all contributors

### ISSUE THREAD

**Issue by skanarul8002** [Bitbox-Connect/Bitbox#350]
### Is there an existing feature request for this?

- [X] I have searched the existing feature requests

### Describe the feature you would like to request

I want to add a page to showcase all the contributors of this website.

### What problem does this feature solve?

This feature provides recognition to contributors and encourages more community involvement. It will also enhance the transparency of contributions to this project.

### Alternative solutions

Alternatively, a section on the homepage could highlight recent contributors, but a dedicated page allows for a more comprehensive display.

### Confirmation

- [X] I have read the Bitbox Contributing Guidelines
- [X] I am a GSSOC-EXT contributor
- [X] I am a HACKTOBERFEST contributor
- [X] I have starred the Bitbox repository
- [X] I would like to help implement this feature

**Comment by skanarul8002** [comment]
@GUNJESH843 , @Harshit7492 please assign me

**Comment by GUNJESH843** [comment]
> @GUNJESH843 , @Harshit7492 please assign me

You can start working on it @skanarul8002

**Comment by skanarul8002** [comment]
@GUNJESH843, i request you to increase level no... please please. I browse 2-3 repo and see a level3 for same issue. Please maintain the levelno.
![IMG_20241103_021800](https://github.com/user-attachments/assets/a85bf50f-82e1-41bf-b69f-feb303aeb440)
