### ISSUE TITLE
[Feature Request]:  Enhanced scroll back button with timeline on it for smoother functioning.

### ISSUE THREAD

**Issue by shriyadindi** [Bitbox-Connect/Bitbox#352]
### Is there an existing feature request for this?

- [X] I have searched the existing feature requests

### Describe the feature you would like to request

 Enhanced scroll back button with timeline on it for smoother functioning.
![Screenshot 2024-10-31 115055](https://github.com/user-attachments/assets/bbecd7aa-e612-42f1-8c62-e95dc5a6bf3b)

### What problem does this feature solve?

Scroll back button

### Confirmation

- [X] I have read the Bitbox Contributing Guidelines
- [X] I am a GSSOC-EXT contributor
- [ ] I am a HACKTOBERFEST contributor
- [X] I have starred the Bitbox repository
- [X] I would like to help implement this feature

**Comment by Anuj3553** [comment]
Hyy @shriyadindi, I'm assigning this issue to you.
