### ISSUE TITLE
[Feature Request]: Adding Remember me to the login page.

### ISSUE THREAD

**Issue by shriyadindi** [Bitbox-Connect/Bitbox#353]
### Is there an existing feature request for this?

- [X] I have searched the existing feature requests

### Describe the feature you would like to request

Adding Remember me to the login page.

### What problem does this feature solve?

user authentication

### Confirmation

- [X] I have read the Bitbox Contributing Guidelines
- [X] I am a GSSOC-EXT contributor
- [ ] I am a HACKTOBERFEST contributor
- [X] I have starred the Bitbox repository
- [X] I would like to help implement this feature

**Comment by Anuj3553** [comment]
Hyy @shriyadindi, I'm assigning this issue to you.
