### ISSUE TITLE
[Bug]: while uploading project the Ui is not good looking and the screen is  not fixing

### ISSUE THREAD

**Issue by VinayLodhi1712** [Bitbox-Connect/Bitbox#355]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Uploading project is not looking good i can enhance the ui of uploading project box and there is a problem that you can see in video attached.

### Expected behavior

proper uploading of project

### Add screenshots (if applicable)

https://github.com/user-attachments/assets/f48b6ab8-a4fd-454c-9648-3eb6803d3ab8

### Confirmation

- [X] I have read the Bitbox Contributing Guidelines
- [X] I am a GSSOC-EXT contributor
- [X] I am a HACKTOBERFEST contributor
- [X] I have starred the Bitbox repository

**Comment by Anuj3553** [comment]
Well done @VinayLodhi1712

**Comment by Anuj3553** [comment]
Can you give star to this repo?
