### ISSUE TITLE
[Feature Request]: Update homepage visitor counter to track unique visitors

### ISSUE THREAD

**Issue by ygowthamr** [Bitbox-Connect/Bitbox#359]
### Is there an existing feature request for this?

- [X] I have searched the existing feature requests

### Describe the feature you would like to request

Currently, the visitor count increments every time a user navigates back to the homepage, even if they have already been counted. Modify the counter to track unique visitors only, ensuring each user is counted once regardless of how many times they revisit the homepage in the same session. Consider using cookies or local storage to store a flag indicating a user has already been counted.

### What problem does this feature solve?

This feature ensures accurate tracking of unique visitors by counting each user only once per session, providing reliable visitor metrics and enhancing the overall user experience.

### Alternative solutions

**Images for reference:**
 - ![image](https://github.com/user-attachments/assets/70eab39b-0190-483a-8186-0a1eb132f3a3)
 
 @Anuj3553

### Confirmation

- [X] I have read the Bitbox Contributing Guidelines
- [X] I am a GSSOC-EXT contributor
- [X] I am a HACKTOBERFEST contributor
- [X] I have starred the Bitbox repository
- [X] I would like to help implement this feature

**Comment by Anuj3553** [comment]
Well done @ygowthamr

**Comment by Anuj3553** [comment]
Can you give star to this repo?

**Comment by ygowthamr** [comment]
done
