### ISSUE TITLE
[Bug]: Newsletter Popup Reappears on Every Page Load

### ISSUE THREAD

**Issue by ygowthamr** [Bitbox-Connect/Bitbox#362]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The newsletter popup is currently appearing every time the page loads, causing inconvenience for users. Once a user clicks the **"No Thanks"** button on the newsletter popup, it should not appear again during future visits for the same user.

### Expected behavior

Once a user clicks **"No Thanks"** on the newsletter popup, it should not reappear for that user unless:
- The user clears their browser cache/cookies.
- A certain time period (e.g., a week) has passed.

### Add screenshots (if applicable)

 - ![image](https://github.com/user-attachments/assets/4e788a47-86c2-4b3b-a518-bffb6e6d461b)

@Anuj3553 pls assign me this issue, give me level, labels.

### Confirmation

- [X] I have read the Bitbox Contributing Guidelines
- [X] I am a GSSOC-EXT contributor
- [X] I am a HACKTOBERFEST contributor
- [X] I have starred the Bitbox repository

**Comment by Anuj3553** [comment]
Hyy @ygowthamr, I'm assigning this issue to you.
