### ISSUE TITLE
[Bug]: the cursor animation is bugged

### ISSUE THREAD

**Issue by AE-Hertz** [Bitbox-Connect/Bitbox#368]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

the cursor animation is still visible even after user's cursor is moved to another display or not at the site,

Expected ;
the cursor animation should disapper if the user's cursor is not on the site.

I will fix this issue. Assign me this

### Expected behavior

-

### Add screenshots (if applicable)

![image](https://github.com/user-attachments/assets/95b3a9ca-a77d-43c1-a0d9-43e68a51abae)

### On which device or platform are you experiencing this bug?

Android, iPhone, Linux, Chrome, Windows

### Confirmation

- [X] I have read the Bitbox Contributing Guidelines
- [X] I am a GSSOC-EXT contributor
- [X] I am a HACKTOBERFEST contributor
- [X] I have starred the Bitbox repository

**Comment by Anuj3553** [comment]
Hyy @AE-Hertz, I'm assigning this issue to you.

**Comment by Anuj3553** [comment]
Can you give star to this repo?

**Comment by AE-Hertz** [comment]
> Can you give star to this repo?

already did 🙂
