### ISSUE TITLE
ADD: Password viewer to login and signup form

### ISSUE THREAD

**Issue by shubhagarwal1** [Bitbox-Connect/Bitbox#37]

**Comment by Dnyaneshpise** [comment]
I would like to work on this issue could you please assign it to me

**Comment by Anuj3553** [comment]
> I would like to work on this issue could you please assign it to me

Hyy @Dnyaneshpise, Can you provide some sample.

**Comment by Anuj3553** [comment]
Okk @shubhagarwal1, Do it on both signup and login page. I'm assigning to you.

**Comment by Dnyaneshpise** [comment]
Doing something like this- https://i.sstatic.net/vbeSq.gif

**Comment by Anuj3553** [comment]
> I would like to work on this issue could you please assign it to me

Sorry @Dnyaneshpise, We have to follow first come first serve order.

**Comment by Anuj3553** [comment]
> Doing something like this- https://i.sstatic.net/vbeSq.gif

This link is broken check it.

**Comment by Anuj3553** [comment]
Hyy @Dnyaneshpise, @shubhagarwal1, Can you give star to this repo.

**Comment by shubhagarwal1** [comment]
> Okk @shubhagarwal1, Do it on both signup and login page. I'm assigning to you.

hey @Anuj3553  i am having trouble setting up only the seen image is visible nothing else is commig
![Screenshot 2024-10-10 at 8 50 52 PM](https://github.com/user-attachments/assets/ff0a6c1e-464c-4b96-8d6a-222ade6fd12c)
can you help me solve this
