### ISSUE TITLE
[Bug]: Home page Is hiding behind Navbar

### ISSUE THREAD

**Issue by IkkiOcean** [Bitbox-Connect/Bitbox#376]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Currently content of homepage is hiding behind the navbar, which should be fixed

### Expected behavior

the content of homepage should be below the navbar for users to see it clearly

### Add screenshots (if applicable)

<img width="1277" alt="Screenshot 2024-11-05 at 1 41 19 AM" src="https://github.com/user-attachments/assets/f3013aee-60d0-4ee7-bb31-48664e88326a">

### On which device or platform are you experiencing this bug?

iPhone, Windows

### Confirmation

- [X] I have read the Bitbox Contributing Guidelines
- [X] I am a GSSOC-EXT contributor
- [ ] I am a HACKTOBERFEST contributor
- [X] I have starred the Bitbox repository

**Comment by Anuj3553** [comment]
Hyy @IkkiOcean, I'm assigning this issue to you.
