### ISSUE TITLE
 Implement Newsletter Functionality

### ISSUE THREAD

**Issue by Sawan-Kushwah** [Bitbox-Connect/Bitbox#393]
### Is there an existing feature request for this?

- [X] I have searched the existing feature requests

### Describe the feature you would like to request

We need to implement a newsletter subscription functionality on our platform, Bitbox. This feature will allow users to enter their name and email to subscribe to our newsletter. Upon successful subscription, users will receive a confirmation email.

### What problem does this feature solve?

https://github.com/user-attachments/assets/7f0d2e9b-cb3d-4051-a12a-276453ef8409

this is how it will work

### Confirmation

- [X] I have read the Bitbox Contributing Guidelines
- [X] I am a GSSOC-EXT contributor
- [X] I am a HACKTOBERFEST contributor
- [X] I have starred the Bitbox repository
- [X] I would like to help implement this feature

**Comment by Anuj3553** [comment]
Hyy @Sawan-Kushwah, I'm assigning this issue to you.
