### ISSUE TITLE
[Bug]: Login page is not Rendering

### ISSUE THREAD

**Issue by IkkiOcean** [Bitbox-Connect/Bitbox#396]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The login page is currently not rendering as expected, with several errors appearing in the console. These errors prevent users from accessing the login functionality, impacting the user experience.

### Expected behavior

The login page should load without any errors, allowing users to enter their credentials and access their accounts.

### Add screenshots (if applicable)

https://github.com/user-attachments/assets/4cfdd61a-0dae-4dff-ab81-ad6e6447d11c

### Confirmation

- [X] I have read the Bitbox Contributing Guidelines
- [X] I am a GSSOC-EXT contributor
- [ ] I am a HACKTOBERFEST contributor
- [X] I have starred the Bitbox repository

**Comment by Anuj3553** [comment]
Hyy @IkkiOcean, I'm assigning this issue to you.
