### ISSUE TITLE
Improving login page ui and header ui

### ISSUE THREAD

**Issue by ganashree1612** [Bitbox-Connect/Bitbox#4]
Hey i am a gssoc contributor and i want to improve the ui of login page and header section can u assign me this issue.

**Comment by ganashree1612** [comment]
![image](https://github.com/user-attachments/assets/3a524e68-bb30-439b-a587-9b20e03a7f08)
here is the updated ui for the login container

**Comment by Harshit7492** [comment]
Already assigned to some one but he is not active i think so firstly share some templete then @Harshit7492  and @Anuj3553  will assigne you this and don't comment for label we will also add if you complete the task

**Comment by ganashree1612** [comment]
sure here is a template 
![image](https://github.com/user-attachments/assets/87a33846-98c0-43c8-a938-765e6356f2e7)
![image](https://github.com/user-attachments/assets/c7d1ab9a-a765-4e85-a18f-37870769b222)

**Comment by Anuj3553** [comment]
Hi @ganashree1612,

Thank you for sharing your work with us! We will assign you this issue. If you have any questions or need additional information, feel free to add them here. Your contributions are greatly appreciated! 😊

**Comment by Anuj3553** [comment]
Well done, @ganashree1612, on completing the issue! 🎉
Your efforts are truly valued, and the updates you implemented look excellent. Please note that you have removed the "Forgot Password" page issue from your pull request, but we will still provide labels for that contribution. Keep up the great work, and continue contributing your talents!

**Comment by ganashree1612** [comment]
Thank you but the pull request number has not increased does it takes time and should i close this issue

**Comment by Anuj3553** [comment]
Hey @ganashree1612,

We apologize, but we can only assign tags based on your current work level.

**Comment by ganashree1612** [comment]
should i close this issue

**Comment by Anuj3553** [comment]
Yes you can close this issue

**Comment by ganashree1612** [comment]
Changes made

**Comment by Anuj3553** [comment]
Hyy @ganashree1612, Can you do star mark this repo?

**Comment by ganashree1612** [comment]
Sure done👍
