### ISSUE TITLE
[Bug]: Refresh Rendering of Pages not Working

### ISSUE THREAD

**Issue by NK-Works** [Bitbox-Connect/Bitbox#400]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The pages don't render sometimes and shows up error

### Expected behavior

All the websites routes should render properly

### Add screenshots (if applicable)

![image](https://github.com/user-attachments/assets/b6931b81-5df4-44ac-9de3-25f647581d21)
Usually shows up after a refresh sometimes even without a refresh

### Confirmation

- [X] I have read the Bitbox Contributing Guidelines
- [X] I am a GSSOC-EXT contributor
- [X] I am a HACKTOBERFEST contributor
- [X] I have starred the Bitbox repository

**Comment by Anuj3553** [comment]
Hyy @NK-Works, I'm assigning this issue to you.
