### ISSUE TITLE
faq page revamp

### ISSUE THREAD

**Issue by ShivanshPlays** [Bitbox-Connect/Bitbox#404]
![image](https://github.com/user-attachments/assets/b4ad3130-0a51-4029-9743-abbce859be1d)

redesign the faq page

**Comment by Anuj3553** [comment]
Hyy @ShivanshPlays, I'm assigning this issue to you.

**Comment by ShivanshPlays** [comment]
...as the faq page was missing instead of revamping , I added a new faq page

**Comment by ShivanshPlays** [comment]
has updated the design , can you review it
![Screenshot 2024-11-10 013125](https://github.com/user-attachments/assets/b2863d20-76b2-4d01-b5c0-7643c91c55a5)

**Comment by Anuj3553** [comment]
It is good now you can push your commit @ShivanshPlays
