### ISSUE TITLE
[Bug]: Mobile Responsiveness - Grow, Share, and Learn sections layout and padding issues.

### ISSUE THREAD

**Issue by bmukesh23** [Bitbox-Connect/Bitbox#411]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Some content elements in Bitbox are not fully responsive on mobile devices. Specifically, the image and text content in the `Grow`,   `Learn`, and `Share` sections are displayed in a horizontal flex row layout, which does not adapt well to smaller screens. Additionally, the text content has excessive padding, making it appear cramped on mobile.

### Expected behavior

1. Use a flex column layout to stack the image and text vertically.
2. Have padding adjusted to match mobile design requirements for better readability and spacing.

### Add screenshots (if applicable)

![Screenshot 2024-11-07 134202](https://github.com/user-attachments/assets/3a8d06a6-f579-42e5-833e-4b4f91ea5f6c)

### On which device or platform are you experiencing this bug?

Android, Chrome, Windows

### Confirmation

- [X] I have read the Bitbox Contributing Guidelines
- [X] I am a GSSOC-EXT contributor
- [ ] I am a HACKTOBERFEST contributor
- [X] I have starred the Bitbox repository

**Comment by Anuj3553** [comment]
Hyy @bmukesh23, I'm assigning this issue to you.
