### ISSUE TITLE
ENHANCE BLOG PAGE DESIGN 

### ISSUE THREAD

**Issue by Sawan-Kushwah** [Bitbox-Connect/Bitbox#417]
### Is there an existing feature request for this?

- [X] I have searched the existing feature requests

### Describe the feature you would like to request

I have improve uts designing as contributor page

### What problem does this feature solve?

User experience 

### Confirmation

- [X] I have read the Bitbox Contributing Guidelines
- [X] I am a GSSOC-EXT contributor
- [X] I am a HACKTOBERFEST contributor
- [X] I have starred the Bitbox repository
- [X] I would like to help implement this feature

**Comment by Anuj3553** [comment]
Hyy @Sawan-Kushwah, I'm assigning this issue to you and send me the video with PR.
