### ISSUE TITLE
[Bug]: Dark mode bug in singup page

### ISSUE THREAD

**Issue by Sourabh782** [Bitbox-Connect/Bitbox#420]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The signup page content is not vidible in dark mode

### Expected behavior

the text should have proper contrast with background to enhance readiblity

### Add screenshots (if applicable)

![image](https://github.com/user-attachments/assets/55486eea-98f4-44e9-9425-443909f50744)

### On which device or platform are you experiencing this bug?

Chrome

### Confirmation

- [X] I have read the Bitbox Contributing Guidelines
- [X] I am a GSSOC-EXT contributor
- [X] I am a HACKTOBERFEST contributor
- [X] I have starred the Bitbox repository

**Comment by Sourabh782** [comment]
> Can you please assign me

i raised the issue

**Comment by Anuj3553** [comment]
Hyy @Sourabh782, I'm assigning this issue to you.
