### ISSUE TITLE
Implement Discussion Forum with CURD operation & Responsive Design

### ISSUE THREAD

**Issue by Sawan-Kushwah** [Bitbox-Connect/Bitbox#422]
### Is there an existing feature request for this?

- [X] I have searched the existing feature requests

### Describe the feature you would like to request

https://github.com/user-attachments/assets/134a6716-5fea-4d9a-97da-669ab573d8c8

### What problem does this feature solve?

Implemented an interactive discussion forum that allows users to post and view questions and answers. 
All Q&A data is securely stored in localStorage, ensuring persistence even after page refreshes. 
The design is fully responsive, offering a seamless experience across desktop, tablet, and mobile devices. 
This feature makes it easier for users to engage in discussions, ask questions, and view answers without worrying about data loss.

### Confirmation

- [X] I have read the Bitbox Contributing Guidelines
- [X] I am a GSSOC-EXT contributor
- [X] I am a HACKTOBERFEST contributor
- [X] I have starred the Bitbox repository
- [X] I would like to help implement this feature

**Comment by Anuj3553** [comment]
Hyy @Sawan-Kushwah, I'm assigning this issue to you. Make this according to our website color pallate and after this give the video attached with PR.

**Comment by ShivanshPlays** [comment]
@Sawan-Kushwah if the QNA is persisted in localstorage then how will it be displayed to other users? and if not then what is the use of forum, just asking in the light of useful and positive development of the project.

**Comment by ShivanshPlays** [comment]
@Anuj3553 please check the proposal i made for implementing the same functionality. I think it consists of better alternative of persisting data in backend other that localstorage.

PS: this suggestion is in the light of useful and positive development of the project.
The end decision is upto the PA

**Comment by Anuj3553** [comment]
> @Anuj3553 please check the proposal i made for implementing the same functionality. I think it consists of better alternative of persisting data in backend other that localstorage.
> 
> PS: this suggestion is in the light of useful and positive development of the project. The end decision is upto the PA

Yes you are right @ShivanshPlays. Hyy @Sawan-Kushwah, Can you create as well as backend for this?

**Comment by Sawan-Kushwah** [comment]
@ShivanshPlays @Anuj3553 in the next PR i will make backend api for it

**Comment by Sawan-Kushwah** [comment]
So that data get saved successfully on one database and thus how we can show all question and answer

**Comment by ShivanshPlays** [comment]
@Anuj3553 maybe I can work on the backend api?

**Comment by ShivanshPlays** [comment]
I will provide postman testing with screen recording

**Comment by ShivanshPlays** [comment]
if it is fine with @Sawan-Kushwah

**Comment by Sawan-Kushwah** [comment]
@Anuj3553 @ShivanshPlays i will provide the video where i show how data is being saving on database

**Comment by Anuj3553** [comment]
> @Anuj3553 @ShivanshPlays i will provide the video where i show how data is being saving on database

Okk, then go ahead with this issue.
