### ISSUE TITLE
while uploading blog i am not able to provide my repo link

### ISSUE THREAD

**Issue by Sawan-Kushwah** [Bitbox-Connect/Bitbox#428]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

go to project
click on upload blog 
and try to give github link 

### Expected behavior

i should able to provide github link

### On which device or platform are you experiencing this bug?

Chrome

### Confirmation

- [X] I have read the Bitbox Contributing Guidelines
- [X] I am a GSSOC-EXT contributor
- [X] I am a HACKTOBERFEST contributor
- [X] I have starred the Bitbox repository

**Comment by Anuj3553** [comment]
Hyy @Sawan-Kushwah, I'm assigning this issue to you. Give the video attached with PR.
