### ISSUE TITLE
Implement Admin functionality to administer all blogs.

### ISSUE THREAD

**Issue by ShivanshPlays** [Bitbox-Connect/Bitbox#430]
add admin functionality to perform read and delete on blogs to monitor and filter the content on the website.

PR1 (edit: completed #435 ): add admin table to the db and necessary backend api for authentication of admin.

PR2: (edit: completed #436  )
add a login page for admin with proper styling and auth functionality
add admin dashboard which displays all blogs with read and delete functionality

this issues can be further extended to add more admin functionalities as per discussion with the PA.

@Anuj3553

**Comment by Anuj3553** [comment]
Hyy @ShivanshPlays, I'm assigning this issue to you. Make this according to our website color pallate and after this give the video attached with PR.

**Comment by ShivanshPlays** [comment]
sure! I will raise the necessary PRs soon
