### ISSUE TITLE
Proposal to add Github bot to Acknowledge Issue

### ISSUE THREAD

**Issue by Abhi9shinde** [Bitbox-Connect/Bitbox#51]
Description:
I propose creating a GitHub bot that automatically responds to new issues with a message thanking users for their contributions and informing them that our team will review it shortly.
When I raised a issue yesterday I saw there was no bot to respond to the issues.
So I would like to work on it

Benefits:
Enhances user experience by providing immediate feedback.
Encourages more contributions to our project.

Please assign this task to me under hacotoberfest, gssoc-ext and I think level 1 would be enough

**Comment by Anuj3553** [comment]
Hyy @Abhi9shinde, I'm assigning this project to you. All the best to you,

**Comment by Anuj3553** [comment]
Can you do star mark to this repository.

**Comment by Abhi9shinde** [comment]
Yes sir, why not
