### ISSUE TITLE
Add placeholder skeleton while data is loading in community page 

### ISSUE THREAD

**Issue by AyushSharma72** [Bitbox-Connect/Bitbox#59]
the api fetches the data from the backend which takes some second at that time the 
screen on community page is blank i will add a placeholder skeleton while the data is loading

![image](https://github.com/user-attachments/assets/11ac5789-5f32-4f12-9a1f-0d13e34bb09f)

please assign this issue to me @Anuj3553

**Comment by Anuj3553** [comment]
Hyy @AyushSharma72, I'm assigning this issue to you.

**Comment by Anuj3553** [comment]
Hyy @AyushSharma72, Can you do star to this repo?

**Comment by AyushSharma72** [comment]
> Hyy @AyushSharma72, Can you do star to this repo?

Yes
