### ISSUE TITLE
fixing the routes

### ISSUE THREAD

**Issue by T-Rahul-prabhu-38** [Bitbox-Connect/Bitbox#6]
the rotes sections are complicated and i would like to work on it and fix it.

Can you please assgin me this so i can work on making this logic easier to read .

**Comment by Harshit7492** [comment]
Can you please explain what you will do to fix the routes then @Harshit7492  or @Anuj3553  assign you this issue and also add label to it

**Comment by T-Rahul-prabhu-38** [comment]
ill just migrate the code from the rotues to route-controller folder , basically routes page will be just 4-5 lines of code. and it will be easy to navigate through routes while debugging.

**Comment by T-Rahul-prabhu-38** [comment]
@Harshit7492 can you assign me this task.

**Comment by Anuj3553** [comment]
Hi @T-Rahul-prabhu-38 

Thank you for sharing your idea with us! We will assign you this issue. If you have any questions or need additional information, feel free to add them here. Your contributions are greatly appreciated! 😊

**Comment by Anuj3553** [comment]
Well done @T-Rahul-prabhu-38 on completing the issue! 🎉

We have given labels based on your work. Your efforts are truly valued, and the updates you implemented look excellent. Keep up the great work, and continue contributing your talents!
