### ISSUE TITLE
Box Layout Error: Text Exceeding Boundaries

### ISSUE THREAD

**Issue by dalvishruti14** [Bitbox-Connect/Bitbox#61]
The text should be contained within the box boundaries. I would like to work on this. @Anuj3553 
![image](https://github.com/user-attachments/assets/7d92f259-16bc-41d0-bfb7-a8b4c2e1fd2c)

**Comment by Anuj3553** [comment]
Hyy @dalvishruti14, It is already assigned to someone.

**Comment by Anuj3553** [comment]
Hyy @dalvishruti14, Can you do star to this repo?
