### ISSUE TITLE
[Bug]:Missing 404 Page

### ISSUE THREAD

**Issue by saurabh-dev-vns** [Bitbox-Connect/Bitbox#65]
Issue:
The website currently lacks a 404 page. When a user tries to access a non-existent page, they are presented with a generic error message or redirected to the homepage. This can lead to confusion and a poor user experience.

I recommend implementing a custom 404 page that provides helpful information to the user, such as a link to the homepage or a search bar.

Expected:
When a user tries to access a non-existent page on the website, they should be presented with a custom 404 page. This page should:

1. Clearly indicate that the page was not found. This could be done with a message such as "Page Not Found" or "Error 404".
2. Provide a helpful message. This could include a brief explanation of what a 404 error is, a suggestion to check the URL, or a link to the website's homepage.

**Comment by saurabh-dev-vns** [comment]
@Anuj3553 , please assign me this issue.

**Comment by Anuj3553** [comment]
Hyy @saurabh-dev-vns, I'm assigning this issue to you.
