### ISSUE TITLE
add forgot password page   

### ISSUE THREAD

**Issue by ganashree1612** [Bitbox-Connect/Bitbox#7]
I want to add forgot password section where user can chaneg their password 
![image](https://github.com/user-attachments/assets/a0f03c42-82ba-460e-a883-491e20c46269)
![image](https://github.com/user-attachments/assets/63ca9b8d-0f3b-4122-9750-d30d144bab2d)

**Comment by Anuj3553** [comment]
Hi @ganashree1612 ,

Thank you for sharing your idea with us! We will assign you this issue. If you have any questions or need additional information, feel free to add them here. Your contributions are greatly appreciated! 😊

**Comment by ganashree1612** [comment]
As i have raised to isssues i have worked on those two and sending pull request for both at the same time is it fine

**Comment by Anuj3553** [comment]
> As i have raised two isssues i have worked on those two and sending pull request for both at the same time is it fine

No @ganashree1612 you have to send pull request by different time but there is no issue that you have worked on both issue that you are selected. For ease of pull request you can make separate folder on your local system.

**Comment by Anuj3553** [comment]
Hyy @ganashree1612,

If you have any doubts, you can also discuss the problem with @GUNJESH843 and @Nehabarnwal24, who are the mentors assigned to this project by GSSoC.

**Comment by ganashree1612** [comment]
closing the issue as it is resolved i hope u add the labels

**Comment by Anuj3553** [comment]
Sorry, @ganashree1612,

I see that you have closed this issue. We assigned all the labels to your first issue, but that's no problem—I’ve added the tags here as well. If you have any doubts or need additional information, feel free to let me know. Keep contributing!

**Comment by ganashree1612** [comment]
should i repopen the issue inorder to get the labels its showing no pull request what should be done here

**Comment by Anuj3553** [comment]
> should i repopen the issue inorder to get the labels its showing no pull request what should be done here and also its not showing merged symbol

No worry about this. Everything is okk.

**Comment by ganashree1612** [comment]
Thank you
