### ISSUE TITLE
Add mini chatbot to the website

### ISSUE THREAD

**Issue by say-het** [Bitbox-Connect/Bitbox#78]
Hey @Anuj3553 I have a great Idea.

 - Adding a mini AI based chatbot to website.

I am already working on this, please assign me this under gssoc-ext so I can raise a PR.

Little about me: I am an experienced contributor as I have successfully completed GSSoC-2024, Hacktoberfest-2020 and Hacktoberfest-2023.

**Comment by Anuj3553** [comment]
Hyy @say-het, I'm assigning this issue to you.
