### ISSUE TITLE
Feeback form can be upgraded

### ISSUE THREAD

**Issue by Jay-1409** [Bitbox-Connect/Bitbox#80]
I think we can have a more comprehensive feedback form 

- Subject or Topic: A dropdown or text field for users to specify the subject of their feedback (e.g., website design, functionality, content, etc.).

i would like to do the following additions: 

- Date of Visit: A date picker to record when the user visited the website.

- Device Used: Options to specify the type of device used (desktop, tablet, mobile).

- Suggestions for Improvement: An open-ended text area for users to provide specific suggestions or comments.

- Visual Rating System: Consider using star ratings or smiley faces for a more engaging rating experience.

- Priority Level: A dropdown to let users indicate the urgency of their feedback (e.g., low, medium, high).

- Confirmation Message: A message indicating that their feedback has been received successfully after submission.

**Comment by Anuj3553** [comment]
Hyy @Jay-1409, I'm assigning this issue to you.

**Comment by Jay-1409** [comment]
okayy ill start my work.

**Comment by Anuj3553** [comment]
Hyy @Jay-1409, Can you star mark to this repo?
