### ISSUE TITLE
Darken Hover Effect on 'Start Now' button

### ISSUE THREAD

**Issue by ShrutiDesai7** [Bitbox-Connect/Bitbox#81]
I noticed that the hover effect on the 'Start Now' button does not change the color significantly.
To improve the visibility of the hover effect, I suggest darkening the color when the button is hovered over. 

https://github.com/user-attachments/assets/055b58db-f501-42a9-8758-c5a32223258e

If this suggestion is approved, I’d be happy to make the changes.
Assign this to me.

**Comment by Anuj3553** [comment]
You can close this issue because you already raise your issue for this problem.
