### ISSUE TITLE
To have the myprofile page fetch details and display during signup/login

### ISSUE THREAD

**Issue by ayush-848** [Bitbox-Connect/Bitbox#86]
To have the myprofile page fetch details and display during signup/login

**Comment by Anuj3553** [comment]
Hyy @ayush-848, I'm assigning issue to you.

**Comment by Anuj3553** [comment]
Hyy @ayush-848, Can you give star to the repo?

**Comment by ayush-848** [comment]
@Anuj3553 
![image](https://github.com/user-attachments/assets/51822207-fc96-425a-853b-f4186501a7ef)
the navbar is not showing after setting both the client and server

**Comment by Anuj3553** [comment]
Pull again code. One contributor solved this problem.

**Comment by ayush-848** [comment]
@Anuj3553 too many issues there

I registered but

![image](https://github.com/user-attachments/assets/ae8a9756-f868-44f9-8cc5-1b88ab47fb82)

**Comment by ayush-848** [comment]
@Anuj3553 there is a major security flaw and logic flaw in the code. Can you give me a link to connect to discord VC whenever you are free??

**Comment by Anuj3553** [comment]
> @Anuj3553 there is a major security flaw and logical flaw in the code

Okk I'll check soon this problem.

**Comment by ayush-848** [comment]
> > @Anuj3553 there is a major security flaw and logical flaw in the code
> 
> Okk I'll check soon this problem.

Password is not hashed when it gets saved in db during sign up and in login it is compared as hash 
![image](https://github.com/user-attachments/assets/c029c6c5-0bd6-4034-a286-498fc31648ab)

**Comment by Anuj3553** [comment]
> > > @Anuj3553 there is a major security flaw and logical flaw in the code
> > 
> > 
> > Okk I'll check soon this problem.
> 
> Password is not hashed when it gets saved in db during sign up and in login it is compared as hash ![image](https://private-user-images.githubusercontent.com/126975547/376040419-c029c6c5-0bd6-4034-a286-498fc31648ab.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg4Mjg3NTgsIm5iZiI6MTcyODgyODQ1OCwicGF0aCI6Ii8xMjY5NzU1NDcvMzc2MDQwNDE5LWMwMjljNmM1LTBiZDYtNDAzNC1hMjg2LTQ5OGZjMzE2NDhhYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxM1QxNDA3MzhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jYjVmZGUwYzM5ZWIyM2UzNTJiYzAxNjA3YTRkNDY3NmUyZTdlY2NhOGNiZDE5M2ZkY2RkMWU4NTgwZWU1NmQ0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.UJngJ977ZKBIye-D0kGmmnYBodzND27rV9amzRDZHf0)

I implemented the hash functionality. How can be this problem appear.

**Comment by ayush-848** [comment]
> > > > @Anuj3553 there is a major security flaw and logical flaw in the code
> > > 
> > > 
> > > Okk I'll check soon this problem.
> > 
> > 
> > Password is not hashed when it gets saved in db during sign up and in login it is compared as hash ![image](https://private-user-images.githubusercontent.com/126975547/376040419-c029c6c5-0bd6-4034-a286-498fc31648ab.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg4Mjg3NTgsIm5iZiI6MTcyODgyODQ1OCwicGF0aCI6Ii8xMjY5NzU1NDcvMzc2MDQwNDE5LWMwMjljNmM1LTBiZDYtNDAzNC1hMjg2LTQ5OGZjMzE2NDhhYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxM1QxNDA3MzhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jYjVmZGUwYzM5ZWIyM2UzNTJiYzAxNjA3YTRkNDY3NmUyZTdlY2NhOGNiZDE5M2ZkY2RkMWU4NTgwZWU1NmQ0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.UJngJ977ZKBIye-D0kGmmnYBodzND27rV9amzRDZHf0)
> 
> I implemented the hash functionality. How can be this problem appear.

@Anuj3553 the password is not saved as hashed during signup

**Comment by Anuj3553** [comment]
> > > > > @Anuj3553 there is a major security flaw and logical flaw in the code
> > > > 
> > > > 
> > > > Okk I'll check soon this problem.
> > > 
> > > 
> > > Password is not hashed when it gets saved in db during sign up and in login it is compared as hash ![image](https://private-user-images.githubusercontent.com/126975547/376040419-c029c6c5-0bd6-4034-a286-498fc31648ab.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg4Mjg3NTgsIm5iZiI6MTcyODgyODQ1OCwicGF0aCI6Ii8xMjY5NzU1NDcvMzc2MDQwNDE5LWMwMjljNmM1LTBiZDYtNDAzNC1hMjg2LTQ5OGZjMzE2NDhhYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxM1QxNDA3MzhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jYjVmZGUwYzM5ZWIyM2UzNTJiYzAxNjA3YTRkNDY3NmUyZTdlY2NhOGNiZDE5M2ZkY2RkMWU4NTgwZWU1NmQ0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.UJngJ977ZKBIye-D0kGmmnYBodzND27rV9amzRDZHf0)
> > 
> > 
> > I implemented the hash functionality. How can be this problem appear.
> 
> @Anuj3553 the password is not saved as hashed during signup ![image](https://private-user-images.githubusercontent.com/126975547/376044937-aa838935-9466-42a0-81de-92c7484fae4d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg4ODY5MTIsIm5iZiI6MTcyODg4NjYxMiwicGF0aCI6Ii8xMjY5NzU1NDcvMzc2MDQ0OTM3LWFhODM4OTM1LTk0NjYtNDJhMC04MWRlLTkyYzc0ODRmYWU0ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxNFQwNjE2NTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03OTJiYTAwNzYxMjU4NTE5ZGQ1OWJmYzAxOWY1OTBhOTU3ZDM1NzY0YWRjOGVjZTdkYmY5MjQ3OTJlZTU5NDdmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.Nkimv3ydYVgfvMJ8s9IvCBti1OYghO-RIcF_rlpsDBA)

Okay, Can you implement this thing?

**Comment by ayush-848** [comment]
> > > > > > @Anuj3553 there is a major security flaw and logical flaw in the code
> > > > > 
> > > > > 
> > > > > Okk I'll check soon this problem.
> > > > 
> > > > 
> > > > Password is not hashed when it gets saved in db during sign up and in login it is compared as hash ![image](https://private-user-images.githubusercontent.com/126975547/376040419-c029c6c5-0bd6-4034-a286-498fc31648ab.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg4Mjg3NTgsIm5iZiI6MTcyODgyODQ1OCwicGF0aCI6Ii8xMjY5NzU1NDcvMzc2MDQwNDE5LWMwMjljNmM1LTBiZDYtNDAzNC1hMjg2LTQ5OGZjMzE2NDhhYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxM1QxNDA3MzhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jYjVmZGUwYzM5ZWIyM2UzNTJiYzAxNjA3YTRkNDY3NmUyZTdlY2NhOGNiZDE5M2ZkY2RkMWU4NTgwZWU1NmQ0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.UJngJ977ZKBIye-D0kGmmnYBodzND27rV9amzRDZHf0)
> > > 
> > > 
> > > I implemented the hash functionality. How can be this problem appear.
> > 
> > 
> > @Anuj3553 the password is not saved as hashed during signup ![image](https://private-user-images.githubusercontent.com/126975547/376044937-aa838935-9466-42a0-81de-92c7484fae4d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg4ODY5MTIsIm5iZiI6MTcyODg4NjYxMiwicGF0aCI6Ii8xMjY5NzU1NDcvMzc2MDQ0OTM3LWFhODM4OTM1LTk0NjYtNDJhMC04MWRlLTkyYzc0ODRmYWU0ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxNFQwNjE2NTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03OTJiYTAwNzYxMjU4NTE5ZGQ1OWJmYzAxOWY1OTBhOTU3ZDM1NzY0YWRjOGVjZTdkYmY5MjQ3OTJlZTU5NDdmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.Nkimv3ydYVgfvMJ8s9IvCBti1OYghO-RIcF_rlpsDBA)
> 
> Okay, Can you implement this thing?

Sure

**Comment by ayush-848** [comment]
@Anuj3553 fixed the signup part
![image](https://github.com/user-attachments/assets/b0b536ba-9733-4487-a8a6-c4a84284c3c5)
![image](https://github.com/user-attachments/assets/7354968f-e709-4146-9f6e-7c2bd4544c7b)

**Comment by ayush-848** [comment]
@Anuj3553 for now merge this part and test them before merging
I will then do the some other stuffs to fetch the details
