### ISSUE TITLE
Creating a Project Upload form

### ISSUE THREAD

**Issue by sejals23** [Bitbox-Connect/Bitbox#93]
A project submission form on a website with project uploads is highly beneficial.

1. Streamlined Submission Process:
It allows users to easily submit their projects directly on the website, ensuring all required information (like project description, files, and details) is collected in one go.
2. Consistency:
By having predefined fields (e.g., project title, category, and tags), it ensures that all submissions follow a consistent format, making it easier to review and manage.
3. Improved User Experience:
Visitors can submit projects without needing to contact the admin or use external platforms, making the process quicker and more user-friendly.
4. Automation:
You can automate tasks like notifications, project approvals, or categorization based on the form inputs, reducing manual work.

Overall, it enhances efficiency, improves project management, and offers a seamless experience for both users and website administrators.

**Comment by Anuj3553** [comment]
> A project submission form on a website with project uploads is highly beneficial.
> 
> 1. Streamlined Submission Process:
>    It allows users to easily submit their projects directly on the website, ensuring all required information (like project description, files, and details) is collected in one go.
> 2. Consistency:
>    By having predefined fields (e.g., project title, category, and tags), it ensures that all submissions follow a consistent format, making it easier to review and manage.
> 3. Improved User Experience:
>    Visitors can submit projects without needing to contact the admin or use external platforms, making the process quicker and more user-friendly.
> 4. Automation:
>    You can automate tasks like notifications, project approvals, or categorization based on the form inputs, reducing manual work.
> 
> Overall, it enhances efficiency, improves project management, and offers a seamless experience for both users and website administrators.

Hyy @sejals23, I'm assigning issue to you.
