### ISSUE TITLE
Frontend rendering fails because of missing import

### ISSUE THREAD

**Issue by mehul-m-prajapati** [Bitbox-Connect/Bitbox#95]
![e1](https://github.com/user-attachments/assets/0337fd1a-0552-411d-81dc-2ea189072ab4)

**Comment by mehul-m-prajapati** [comment]
- After adding missing import, it works fine.

**Comment by Anuj3553** [comment]
Hyy @mehul-m-prajapati, I'm assigning this issue to you.

**Comment by mehul-m-prajapati** [comment]
thanks @Anuj3553

**Comment by Anuj3553** [comment]
Well done @mehul-m-prajapati, Can you give star to this repo?

**Comment by mehul-m-prajapati** [comment]
> Well done @mehul-m-prajapati, Can you give star to this repo?

okay, done @Anuj3553
