### ISSUE TITLE
[bug] : CSS in input Field in Dark Mode error

### ISSUE THREAD

**Issue by anothercoder-nik** [Bitbox-Connect/Bitbox#98]
The input fields on the Signup Page in dark mode are not showing text on typing. This is the video regarding it.

https://github.com/user-attachments/assets/1b0389a2-893b-4c2a-9679-c68aa9a50109

**Here I clicked on the input field still no typed text visible**
![issue](https://github.com/user-attachments/assets/de402dd9-736c-4f06-94e6-6fdb21e5ac38)

I can fix this issue and can optimize this Signup page for the dark mode and also the LogIn page.
This issue is part of the GSSoC-Ext and Hacktoberfest labels, and solving this feature will enhance user interaction.

Could you please assign this issue to me? I am eager to work on it and contribute to the project.

[GSSoC-ext]
[Hacktoberfest]

**Comment by Anuj3553** [comment]
Hyy @anothercoder-nik, I'm assigning this issue to you.
